"""
Auto-generated by PythonGenerator. Do not edit manually.
"""

from __future__ import annotations

import json
import math as _math
from dataclasses import dataclass, field
from typing import Any, Callable, List, Optional


@dataclass
class AutoReference:
    type: str = field(default="AutoReference", init=False)
    name: str = ""

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        d["name"] = _to_dict(self.name)
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class Deadline:
    type: str = field(default="Deadline", init=False)
    deadline: AutoAction = None
    others: List[AutoAction] = field(default_factory=list)

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        d["deadline"] = _to_dict(self.deadline)
        d["others"] = _to_dict(self.others)
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class Sequence:
    type: str = field(default="Sequence", init=False)
    actions: List[AutoAction] = field(default_factory=list)

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        d["actions"] = _to_dict(self.actions)
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class Parallel:
    type: str = field(default="Parallel", init=False)
    actions: List[AutoAction] = field(default_factory=list)

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        d["actions"] = _to_dict(self.actions)
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class Race:
    type: str = field(default="Race", init=False)
    actions: List[AutoAction] = field(default_factory=list)

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        d["actions"] = _to_dict(self.actions)
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self

from . import units


@dataclass
class Wait:
    type: str = field(default="Wait", init=False)
    delay: units.Measure = None

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        d["delay"] = _to_dict(self.delay)
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class Print:
    type: str = field(default="Print", init=False)
    message: str = ""

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        d["message"] = _to_dict(self.message)
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class NetworkConfigurableWait:
    type: str = field(default="NetworkConfigurableWait", init=False)
    name: str = ""
    default_delay: units.Measure = None

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        d["name"] = _to_dict(self.name)
        d["defaultDelay"] = _to_dict(self.default_delay)
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class Rotation2d:
    degrees: float = 0.0

    def to_dict(self) -> dict:
        d: dict = {}
        d["degrees"] = _to_dict(self.degrees)
        return d

    @property
    def radians(self) -> float:
        return _math.radians(self.degrees)

    @property
    def cos(self) -> float:
        return _math.cos(self.radians)

    @property
    def sin(self) -> float:
        return _math.sin(self.radians)

    @staticmethod
    def from_radians(radians: float) -> Rotation2d:
        return Rotation2d(degrees=_math.degrees(radians))

    def plus(self, other: Rotation2d) -> Rotation2d:
        return Rotation2d(degrees=self.degrees + other.degrees)

    def minus(self, other: Rotation2d) -> Rotation2d:
        return Rotation2d(degrees=self.degrees - other.degrees)

    def unary_minus(self) -> Rotation2d:
        return Rotation2d(degrees=-self.degrees)

    def rotate_by(self, other: Rotation2d) -> Rotation2d:
        return self.plus(other)

    def __neg__(self) -> Rotation2d:
        return self.unary_minus()

    def __add__(self, other: Rotation2d) -> Rotation2d:
        return self.plus(other)

    def __sub__(self, other: Rotation2d) -> Rotation2d:
        return self.minus(other)


@dataclass
class Translation2d:
    x: float = 0.0
    y: float = 0.0

    def to_dict(self) -> dict:
        d: dict = {}
        d["x"] = _to_dict(self.x)
        d["y"] = _to_dict(self.y)
        return d

    @property
    def norm(self) -> float:
        return _math.hypot(self.x, self.y)

    def plus(self, other: Translation2d) -> Translation2d:
        return Translation2d(x=self.x + other.x, y=self.y + other.y)

    def minus(self, other: Translation2d) -> Translation2d:
        return Translation2d(x=self.x - other.x, y=self.y - other.y)

    def unary_minus(self) -> Translation2d:
        return Translation2d(x=-self.x, y=-self.y)

    def times(self, scalar: float) -> Translation2d:
        return Translation2d(x=self.x * scalar, y=self.y * scalar)

    def div(self, scalar: float) -> Translation2d:
        return Translation2d(x=self.x / scalar, y=self.y / scalar)

    def rotate_by(self, rotation: Rotation2d) -> Translation2d:
        c = rotation.cos
        s = rotation.sin
        return Translation2d(x=self.x * c - self.y * s, y=self.x * s + self.y * c)

    def distance(self, other: Translation2d) -> float:
        return self.minus(other).norm

    def __neg__(self) -> Translation2d:
        return self.unary_minus()

    def __add__(self, other: Translation2d) -> Translation2d:
        return self.plus(other)

    def __sub__(self, other: Translation2d) -> Translation2d:
        return self.minus(other)

    def __mul__(self, scalar: float) -> Translation2d:
        return self.times(scalar)

    def __truediv__(self, scalar: float) -> Translation2d:
        return self.div(scalar)

    def to_pose2d(self, rotation: Optional[Rotation2d] = None) -> Pose2d:
        """Convert to a Pose2d, optionally with a rotation (defaults to 0 deg)."""
        return Pose2d(
            translation=Translation2d(x=self.x, y=self.y),
            rotation=rotation if rotation is not None else Rotation2d(),
        )


@dataclass
class Pose2d:
    rotation: Rotation2d = field(default_factory=Rotation2d)
    translation: Translation2d = field(default_factory=Translation2d)

    def to_dict(self) -> dict:
        d: dict = {}
        d["rotation"] = _to_dict(self.rotation)
        d["translation"] = _to_dict(self.translation)
        return d

    def plus(self, other: Transform2d) -> Pose2d:
        """Apply a transform (equivalent to transform_by)."""
        return self.transform_by(other)

    def transform_by(self, transform: Transform2d) -> Pose2d:
        """Apply a Transform2d to this pose (WPILib transformBy)."""
        t_trans = transform.translation if transform.translation else Translation2d()
        t_rot = transform.rotation if transform.rotation else Rotation2d()
        new_translation = self.translation.plus(t_trans.rotate_by(self.rotation))
        new_rotation = self.rotation.plus(t_rot)
        return Pose2d(translation=new_translation, rotation=new_rotation)

    def translate_by(self, translation: Translation2d) -> Pose2d:
        """Translate this pose by a Translation2d (no rotation change)."""
        return Pose2d(
            translation=self.translation.plus(translation),
            rotation=Rotation2d(degrees=self.rotation.degrees),
        )

    def rotate_by(self, rotation: Rotation2d) -> Pose2d:
        """Rotate this pose by a Rotation2d."""
        return Pose2d(
            translation=self.translation.rotate_by(rotation),
            rotation=self.rotation.plus(rotation),
        )

    def rotate_around(self, point: Translation2d, rotation: Rotation2d) -> Pose2d:
        """Rotate this pose around a given point."""
        new_translation = self.translation.minus(point).rotate_by(rotation).plus(point)
        new_rotation = self.rotation.plus(rotation)
        return Pose2d(translation=new_translation, rotation=new_rotation)

    def relative_to(self, other: Pose2d) -> Pose2d:
        """Express this pose relative to other's coordinate frame."""
        inv_rot = other.rotation.unary_minus()
        delta = self.translation.minus(other.translation).rotate_by(inv_rot)
        new_rot = self.rotation.minus(other.rotation)
        return Pose2d(translation=delta, rotation=new_rot)

    def inverse(self) -> Pose2d:
        inv_rot = self.rotation.unary_minus()
        inv_trans = self.translation.unary_minus().rotate_by(inv_rot)
        return Pose2d(translation=inv_trans, rotation=inv_rot)

    def to_pose3d(self, z: float = 0.0) -> Pose3d:
        return Pose3d(
            translation=Translation3d(x=self.translation.x, y=self.translation.y, z=z),
            rotation=Rotation3d(yaw=self.rotation.degrees),
        )

    def to_translation2d(self) -> Translation2d:
        return Translation2d(x=self.translation.x, y=self.translation.y)


@dataclass
class APTarget:
    reference: Pose2d = field(default_factory=Pose2d)
    entry_angle: Optional[Rotation2d] = None
    velocity: float = 0.0
    rotation_radius: Optional[units.Measure] = None

    def to_dict(self) -> dict:
        d: dict = {}
        d["reference"] = _to_dict(self.reference)
        if self.entry_angle is not None:
            d["entryAngle"] = _to_dict(self.entry_angle)
        d["velocity"] = _to_dict(self.velocity)
        if self.rotation_radius is not None:
            d["rotationRadius"] = _to_dict(self.rotation_radius)
        return d


@dataclass
class APConstraints:
    velocity: float = 0.0
    acceleration: float = 0.0
    jerk: float = 0.0

    def to_dict(self) -> dict:
        d: dict = {}
        d["velocity"] = _to_dict(self.velocity)
        d["acceleration"] = _to_dict(self.acceleration)
        d["jerk"] = _to_dict(self.jerk)
        return d


@dataclass
class APProfile:
    constraints: APConstraints = field(default_factory=APConstraints)
    error_x_y: units.Measure = None
    error_theta: units.Measure = None
    beeline_radius: units.Measure = None

    def to_dict(self) -> dict:
        d: dict = {}
        d["constraints"] = _to_dict(self.constraints)
        d["errorXY"] = _to_dict(self.error_x_y)
        d["errorTheta"] = _to_dict(self.error_theta)
        d["beelineRadius"] = _to_dict(self.beeline_radius)
        return d


@dataclass
class PIDGains:
    k_p: float = 0.0
    k_i: float = 0.0
    k_d: float = 0.0
    k_s: float = 0.0
    k_g: float = 0.0
    k_v: float = 0.0
    k_a: float = 0.0

    def to_dict(self) -> dict:
        d: dict = {}
        d["kP"] = _to_dict(self.k_p)
        d["kI"] = _to_dict(self.k_i)
        d["kD"] = _to_dict(self.k_d)
        d["kS"] = _to_dict(self.k_s)
        d["kG"] = _to_dict(self.k_g)
        d["kV"] = _to_dict(self.k_v)
        d["kA"] = _to_dict(self.k_a)
        return d


@dataclass
class AutoPilotAction:
    type: str = field(default="AutoPilotAction", init=False)
    target: APTarget = field(default_factory=APTarget)
    profile: Optional[APProfile] = None
    constraints: Optional[APConstraints] = None
    pid_gains: Optional[PIDGains] = None
    can_mirror: Optional[bool] = None

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        d["target"] = _to_dict(self.target)
        if self.profile is not None:
            d["profile"] = _to_dict(self.profile)
        if self.constraints is not None:
            d["constraints"] = _to_dict(self.constraints)
        if self.pid_gains is not None:
            d["pidGains"] = _to_dict(self.pid_gains)
        if self.can_mirror is not None:
            d["canMirror"] = _to_dict(self.can_mirror)
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class XBasedAutoPilotAction:
    type: str = field(default="XBasedAutoPilotAction", init=False)
    target: APTarget = field(default_factory=APTarget)
    profile: Optional[APProfile] = None
    constraints: Optional[APConstraints] = None
    pid_gains: Optional[PIDGains] = None
    can_mirror: Optional[bool] = None

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        d["target"] = _to_dict(self.target)
        if self.profile is not None:
            d["profile"] = _to_dict(self.profile)
        if self.constraints is not None:
            d["constraints"] = _to_dict(self.constraints)
        if self.pid_gains is not None:
            d["pidGains"] = _to_dict(self.pid_gains)
        if self.can_mirror is not None:
            d["canMirror"] = _to_dict(self.can_mirror)
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class StopDriveAction:
    type: str = field(default="StopDriveAction", init=False)
    can_mirror: Optional[bool] = None

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        if self.can_mirror is not None:
            d["canMirror"] = _to_dict(self.can_mirror)
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class FollowPathPlannerPath:
    type: str = field(default="FollowPathPlannerPath", init=False)
    path_name: str = ""
    mirror_path: bool = False
    can_mirror: Optional[bool] = None

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        d["pathName"] = _to_dict(self.path_name)
        d["mirrorPath"] = _to_dict(self.mirror_path)
        if self.can_mirror is not None:
            d["canMirror"] = _to_dict(self.can_mirror)
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class DeployIntakeAction:
    type: str = field(default="DeployIntakeAction", init=False)

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class StowIntakeAction:
    type: str = field(default="StowIntakeAction", init=False)

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class ClimbSearchAction:
    type: str = field(default="ClimbSearchAction", init=False)

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class ClimbHangAction:
    type: str = field(default="ClimbHangAction", init=False)

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class StartShooting:
    type: str = field(default="StartShooting", init=False)

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class StopShooting:
    type: str = field(default="StopShooting", init=False)

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


AutoAction = Optional[AutoReference | Deadline | Sequence | Parallel | Race | Wait | Print | NetworkConfigurableWait | AutoPilotAction | XBasedAutoPilotAction | StopDriveAction | FollowPathPlannerPath | DeployIntakeAction | StowIntakeAction | ClimbSearchAction | ClimbHangAction | StartShooting | StopShooting]


_add_command_hook: Callable[[Any], None] | None = None


def set_add_command_hook(hook: Callable[[Any], None]) -> None:
    global _add_command_hook
    _add_command_hook = hook


def _call_hook(obj: Any) -> None:
    if _add_command_hook is not None:
        _add_command_hook(obj)


def _to_dict(obj: Any) -> Any:
    """Recursively convert an object to a JSON-serializable dict."""
    if obj is None:
        return None
    if hasattr(obj, 'to_dict'):
        return obj.to_dict()
    if isinstance(obj, list):
        return [_to_dict(item) for item in obj]
    if isinstance(obj, dict):
        return {k: _to_dict(v) for k, v in obj.items()}
    return obj


@dataclass
class Auto:
    root_action: AutoAction = None
    can_be_mirrored: Optional[bool] = None
    should_be_flipped: Optional[bool] = None

    def to_dict(self) -> dict:
        d: dict = {}
        d["rootAction"] = _to_dict(self.root_action)
        if self.can_be_mirrored is not None:
            d["canBeMirrored"] = _to_dict(self.can_be_mirrored)
        if self.should_be_flipped is not None:
            d["shouldBeFlipped"] = _to_dict(self.should_be_flipped)
        return d


@dataclass
class Transform2d:
    rotation: Rotation2d = field(default_factory=Rotation2d)
    translation: Translation2d = field(default_factory=Translation2d)

    def to_dict(self) -> dict:
        d: dict = {}
        d["rotation"] = _to_dict(self.rotation)
        d["translation"] = _to_dict(self.translation)
        return d

    def plus(self, other: Transform2d) -> Transform2d:
        """Compose two transforms."""
        return Transform2d(
            translation=self.translation.plus(other.translation.rotate_by(self.rotation)),
            rotation=self.rotation.plus(other.rotation),
        )

    def inverse(self) -> Transform2d:
        inv_rot = self.rotation.unary_minus()
        inv_trans = self.translation.unary_minus().rotate_by(inv_rot)
        return Transform2d(translation=inv_trans, rotation=inv_rot)


@dataclass
class Rotation3d:
    roll: float = 0.0
    pitch: float = 0.0
    yaw: float = 0.0

    def to_dict(self) -> dict:
        d: dict = {}
        d["roll"] = _to_dict(self.roll)
        d["pitch"] = _to_dict(self.pitch)
        d["yaw"] = _to_dict(self.yaw)
        return d

    def plus(self, other: Rotation3d) -> Rotation3d:
        return Rotation3d(roll=self.roll + other.roll, pitch=self.pitch + other.pitch, yaw=self.yaw + other.yaw)

    def minus(self, other: Rotation3d) -> Rotation3d:
        return Rotation3d(roll=self.roll - other.roll, pitch=self.pitch - other.pitch, yaw=self.yaw - other.yaw)

    def unary_minus(self) -> Rotation3d:
        return Rotation3d(roll=-self.roll, pitch=-self.pitch, yaw=-self.yaw)

    def to_rotation2d(self) -> Rotation2d:
        return Rotation2d(degrees=self.yaw)


@dataclass
class Translation3d:
    x: float = 0.0
    y: float = 0.0
    z: float = 0.0

    def to_dict(self) -> dict:
        d: dict = {}
        d["x"] = _to_dict(self.x)
        d["y"] = _to_dict(self.y)
        d["z"] = _to_dict(self.z)
        return d

    def plus(self, other: Translation3d) -> Translation3d:
        return Translation3d(x=self.x + other.x, y=self.y + other.y, z=self.z + other.z)

    def minus(self, other: Translation3d) -> Translation3d:
        return Translation3d(x=self.x - other.x, y=self.y - other.y, z=self.z - other.z)

    def unary_minus(self) -> Translation3d:
        return Translation3d(x=-self.x, y=-self.y, z=-self.z)

    def times(self, scalar: float) -> Translation3d:
        return Translation3d(x=self.x * scalar, y=self.y * scalar, z=self.z * scalar)

    @property
    def norm(self) -> float:
        return _math.sqrt(self.x ** 2 + self.y ** 2 + self.z ** 2)

    def distance(self, other: Translation3d) -> float:
        return self.minus(other).norm

    def to_translation2d(self) -> Translation2d:
        return Translation2d(x=self.x, y=self.y)

    def to_pose2d(self, rotation: Optional[Rotation2d] = None) -> Pose2d:
        """Convert to a Pose2d (dropping Z), optionally with a rotation."""
        return Pose2d(
            translation=Translation2d(x=self.x, y=self.y),
            rotation=rotation if rotation is not None else Rotation2d(),
        )


@dataclass
class Transform3d:
    rotation: Rotation3d = field(default_factory=Rotation3d)
    translation: Translation3d = field(default_factory=Translation3d)

    def to_dict(self) -> dict:
        d: dict = {}
        d["rotation"] = _to_dict(self.rotation)
        d["translation"] = _to_dict(self.translation)
        return d

    def plus(self, other: Transform3d) -> Transform3d:
        return Transform3d(
            translation=self.translation.plus(other.translation),
            rotation=self.rotation.plus(other.rotation),
        )

    def inverse(self) -> Transform3d:
        return Transform3d(
            translation=self.translation.unary_minus(),
            rotation=self.rotation.unary_minus(),
        )


@dataclass
class Pose3d:
    rotation: Rotation3d = field(default_factory=Rotation3d)
    translation: Translation3d = field(default_factory=Translation3d)

    def to_dict(self) -> dict:
        d: dict = {}
        d["rotation"] = _to_dict(self.rotation)
        d["translation"] = _to_dict(self.translation)
        return d

    def translate_by(self, translation: Translation3d) -> Pose3d:
        return Pose3d(
            translation=self.translation.plus(translation),
            rotation=Rotation3d(roll=self.rotation.roll, pitch=self.rotation.pitch, yaw=self.rotation.yaw),
        )

    def to_pose2d(self) -> Pose2d:
        return Pose2d(
            translation=Translation2d(x=self.translation.x, y=self.translation.y),
            rotation=Rotation2d(degrees=self.rotation.yaw),
        )

    def to_translation2d(self) -> Translation2d:
        return Translation2d(x=self.translation.x, y=self.translation.y)

