"""
Auto-generated by PythonGenerator. Do not edit manually.
"""

from __future__ import annotations

import json
import math as _math
from dataclasses import dataclass, field
from typing import Any, Callable, List, Optional


@dataclass
class AutoReference:
    type: str = field(default="AutoReference", init=False)
    name: str

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        d["name"] = _to_dict(self.name)
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class Deadline:
    type: str = field(default="Deadline", init=False)
    deadline: AutoAction = None
    others: List[AutoAction] = field(default_factory=list)

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        d["deadline"] = _to_dict(self.deadline)
        d["others"] = _to_dict(self.others)
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class Sequence:
    type: str = field(default="Sequence", init=False)
    actions: List[AutoAction] = field(default_factory=list)

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        d["actions"] = _to_dict(self.actions)
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class Parallel:
    type: str = field(default="Parallel", init=False)
    actions: List[AutoAction] = field(default_factory=list)

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        d["actions"] = _to_dict(self.actions)
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class Race:
    type: str = field(default="Race", init=False)
    actions: List[AutoAction] = field(default_factory=list)

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        d["actions"] = _to_dict(self.actions)
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self

from . import units


@dataclass
class Wait:
    type: str = field(default="Wait", init=False)
    delay: units.Measure = None

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        d["delay"] = _to_dict(self.delay)
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class Print:
    type: str = field(default="Print", init=False)
    message: str

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        d["message"] = _to_dict(self.message)
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class Rotation2d:
    degrees: float

    def to_dict(self) -> dict:
        d: dict = {}
        d["degrees"] = _to_dict(self.degrees)
        return d


@dataclass
class Translation2d:
    x: float
    y: float

    def to_dict(self) -> dict:
        d: dict = {}
        d["x"] = _to_dict(self.x)
        d["y"] = _to_dict(self.y)
        return d


@dataclass
class Pose2d:
    rotation: Rotation2d = field(default_factory=Rotation2d)
    translation: Translation2d = field(default_factory=Translation2d)

    def to_dict(self) -> dict:
        d: dict = {}
        d["rotation"] = _to_dict(self.rotation)
        d["translation"] = _to_dict(self.translation)
        return d


@dataclass
class APTarget:
    velocity: float
    reference: Pose2d = field(default_factory=Pose2d)
    entry_angle: Optional[Rotation2d] = None
    rotation_radius: Optional[units.Measure] = None

    def to_dict(self) -> dict:
        d: dict = {}
        d["reference"] = _to_dict(self.reference)
        if self.entry_angle is not None:
            d["entryAngle"] = _to_dict(self.entry_angle)
        d["velocity"] = _to_dict(self.velocity)
        if self.rotation_radius is not None:
            d["rotationRadius"] = _to_dict(self.rotation_radius)
        return d


@dataclass
class APConstraints:
    velocity: float
    acceleration: float
    jerk: float

    def to_dict(self) -> dict:
        d: dict = {}
        d["velocity"] = _to_dict(self.velocity)
        d["acceleration"] = _to_dict(self.acceleration)
        d["jerk"] = _to_dict(self.jerk)
        return d


@dataclass
class APProfile:
    constraints: APConstraints
    error_x_y: units.Measure = None
    error_theta: units.Measure = None
    beeline_radius: units.Measure = None

    def to_dict(self) -> dict:
        d: dict = {}
        d["constraints"] = _to_dict(self.constraints)
        d["errorXY"] = _to_dict(self.error_x_y)
        d["errorTheta"] = _to_dict(self.error_theta)
        d["beelineRadius"] = _to_dict(self.beeline_radius)
        return d


@dataclass
class PIDGains:
    k_p: float
    k_i: float
    k_d: float
    k_s: float
    k_g: float
    k_v: float
    k_a: float

    def to_dict(self) -> dict:
        d: dict = {}
        d["kP"] = _to_dict(self.k_p)
        d["kI"] = _to_dict(self.k_i)
        d["kD"] = _to_dict(self.k_d)
        d["kS"] = _to_dict(self.k_s)
        d["kG"] = _to_dict(self.k_g)
        d["kV"] = _to_dict(self.k_v)
        d["kA"] = _to_dict(self.k_a)
        return d


@dataclass
class AutoPilotAction:
    type: str = field(default="AutoPilotAction", init=False)
    target: APTarget = field(default_factory=APTarget)
    profile: Optional[APProfile] = None
    constraints: Optional[APConstraints] = None
    pid_gains: Optional[PIDGains] = None
    alliance_relative: Optional[bool] = None

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        d["target"] = _to_dict(self.target)
        if self.profile is not None:
            d["profile"] = _to_dict(self.profile)
        if self.constraints is not None:
            d["constraints"] = _to_dict(self.constraints)
        if self.pid_gains is not None:
            d["pidGains"] = _to_dict(self.pid_gains)
        if self.alliance_relative is not None:
            d["allianceRelative"] = _to_dict(self.alliance_relative)
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class XBasedAutoPilotAction:
    type: str = field(default="XBasedAutoPilotAction", init=False)
    target: APTarget = field(default_factory=APTarget)
    profile: Optional[APProfile] = None
    constraints: Optional[APConstraints] = None
    pid_gains: Optional[PIDGains] = None
    alliance_relative: Optional[bool] = None

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        d["target"] = _to_dict(self.target)
        if self.profile is not None:
            d["profile"] = _to_dict(self.profile)
        if self.constraints is not None:
            d["constraints"] = _to_dict(self.constraints)
        if self.pid_gains is not None:
            d["pidGains"] = _to_dict(self.pid_gains)
        if self.alliance_relative is not None:
            d["allianceRelative"] = _to_dict(self.alliance_relative)
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class StopDriveAction:
    type: str = field(default="StopDriveAction", init=False)

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class DeployIntakeAction:
    type: str = field(default="DeployIntakeAction", init=False)

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class StowIntakeAction:
    type: str = field(default="StowIntakeAction", init=False)

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class ClimbSearchAction:
    type: str = field(default="ClimbSearchAction", init=False)

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


@dataclass
class ClimbHangAction:
    type: str = field(default="ClimbHangAction", init=False)

    def to_dict(self) -> dict:
        d: dict = {"type": self.type}
        return d

    def add(self):
        """Adds this command to the current auto and returns itself for chaining."""
        _call_hook(self)
        return self


AutoAction = Optional[AutoReference | Deadline | Sequence | Parallel | Race | Wait | Print | AutoPilotAction | XBasedAutoPilotAction | StopDriveAction | DeployIntakeAction | StowIntakeAction | ClimbSearchAction | ClimbHangAction]


_add_command_hook: Callable[[Any], None] | None = None


def set_add_command_hook(hook: Callable[[Any], None]) -> None:
    global _add_command_hook
    _add_command_hook = hook


def _call_hook(obj: Any) -> None:
    if _add_command_hook is not None:
        _add_command_hook(obj)


def _to_dict(obj: Any) -> Any:
    """Recursively convert an object to a JSON-serializable dict."""
    if obj is None:
        return None
    if hasattr(obj, 'to_dict'):
        return obj.to_dict()
    return obj


@dataclass
class Transform2d:
    rotation: Rotation2d = field(default_factory=Rotation2d)
    translation: Translation2d = field(default_factory=Translation2d)

    def to_dict(self) -> dict:
        d: dict = {}
        d["rotation"] = _to_dict(self.rotation)
        d["translation"] = _to_dict(self.translation)
        return d


@dataclass
class Rotation3d:
    roll: float
    pitch: float
    yaw: float

    def to_dict(self) -> dict:
        d: dict = {}
        d["roll"] = _to_dict(self.roll)
        d["pitch"] = _to_dict(self.pitch)
        d["yaw"] = _to_dict(self.yaw)
        return d


@dataclass
class Translation3d:
    x: float
    y: float
    z: float

    def to_dict(self) -> dict:
        d: dict = {}
        d["x"] = _to_dict(self.x)
        d["y"] = _to_dict(self.y)
        d["z"] = _to_dict(self.z)
        return d


@dataclass
class Transform3d:
    rotation: Rotation3d = field(default_factory=Rotation3d)
    translation: Translation3d = field(default_factory=Translation3d)

    def to_dict(self) -> dict:
        d: dict = {}
        d["rotation"] = _to_dict(self.rotation)
        d["translation"] = _to_dict(self.translation)
        return d


@dataclass
class Pose3d:
    rotation: Rotation3d = field(default_factory=Rotation3d)
    translation: Translation3d = field(default_factory=Translation3d)

    def to_dict(self) -> dict:
        d: dict = {}
        d["rotation"] = _to_dict(self.rotation)
        d["translation"] = _to_dict(self.translation)
        return d

