"""
Auto-generated by PythonGenerator. Do not edit manually.

Provides unit types and measure creation functions that serialize
to the same JSON format the Java robot code expects.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class Measure:
    """A measure with a numeric value and a unit name string."""
    value: float
    unit: str

    def to_dict(self) -> dict:
        return {"value": self.value, "unit": self.unit}


@dataclass
class Unit:
    """A named unit that can create Measure instances."""
    name: str

    def of(self, value: float) -> Measure:
        return Measure(value=value, unit=self.name)


# AngularVelocityPerTime unit type
Rotation_per_Second_per_Second = Unit("Rotation per Second per Second")
# CurrentPerTime unit type
Amp_per_Second = Unit("Amp per Second")
# Voltage unit type
Volt = Unit("Volt")
# LinearVelocityPerTime unit type
Meter_per_Second_per_Second = Unit("Meter per Second per Second")
# Time unit type
Minute = Unit("Minute")
Foot_per_Second_per_Second = Unit("Foot per Second per Second")
# AnglePerTime unit type
Degree_per_Second = Unit("Degree per Second")
# Torque unit type
Inch_Pound_force = Unit("Inch-Pound-force")
Radian_per_Second = Unit("Radian per Second")
# VoltagePerLinearAcceleration unit type
Volt_per_Meter_per_Second_per_Second = Unit("Volt per Meter per Second per Second")
# DimensionlessPerTime unit type
Hertz = Unit("Hertz")
# Distance unit type
Centimeter = Unit("Centimeter")
Inch_Ounce_force = Unit("Inch-Ounce-force")
# DistancePerTime unit type
Inch_per_Second = Unit("Inch per Second")
Meter_Newton = Unit("Meter-Newton")
Degree_per_Second_per_Second = Unit("Degree per Second per Second")
# EnergyPerTime unit type
Watt = Unit("Watt")
Rotation_per_Second = Unit("Rotation per Second")
# Current unit type
Amp = Unit("Amp")
# Force unit type
Newton = Unit("Newton")
# Temperature unit type
Celsius = Unit("Celsius")
Fahrenheit = Unit("Fahrenheit")
G = Unit("G")
Inch = Unit("Inch")
Foot_per_Second = Unit("Foot per Second")
# Energy unit type
Joule = Unit("Joule")
Kelvin = Unit("Kelvin")
Rotation_per_Minute = Unit("Rotation per Minute")
# LinearMomentum unit type
Kilogram_Meter_per_Second = Unit("Kilogram-Meter per Second")
# VoltagePerCurrent unit type
Kiloohm = Unit("Kiloohm")
# Mass unit type
Gram = Unit("Gram")
Millimeter = Unit("Millimeter")
Millihertz = Unit("Millihertz")
Millijoule = Unit("Millijoule")
# Angle unit type
Degree = Unit("Degree")
Rotation = Unit("Rotation")
Foot_Pound_force = Unit("Foot-Pound-force")
Microsecond = Unit("Microsecond")
Radian_per_Second_per_Second = Unit("Radian per Second per Second")
Revolution_per_Second = Unit("Revolution per Second")
Millivolt = Unit("Millivolt")
Rotation_per_Minute_per_Second = Unit("Rotation per Minute per Second")
Revolution = Unit("Revolution")
Kilogram = Unit("Kilogram")
Kilojoule = Unit("Kilojoule")
Radian = Unit("Radian")
Milliwatt = Unit("Milliwatt")
Foot = Unit("Foot")
# AngularMomentum unit type
Kilogram_Meter_per_Second_Meter = Unit("Kilogram-Meter per Second-Meter")
# AngularMomentumPerAngularVelocity unit type
Kilogram_Meter_per_Second_Meter_per_Radian_per_Second = Unit("Kilogram-Meter per Second-Meter per Radian per Second")
Milliohm = Unit("Milliohm")
Volt_per_Radian_per_Second_per_Second = Unit("Volt per Radian per Second per Second")
Volt_per_Radian_per_Second = Unit("Volt per Radian per Second")
# Dimensionless unit type
Percent = Unit("Percent")
Millisecond = Unit("Millisecond")
Pound = Unit("Pound")
Second = Unit("Second")
Meter = Unit("Meter")
Horsepower = Unit("Horsepower")
Meter_per_Second = Unit("Meter per Second")
Milliamp = Unit("Milliamp")
Ounce = Unit("Ounce")
Unitless = Unit("<?>")
Ohm = Unit("Ohm")
Ounce_force = Unit("Ounce-force")
Pound_force = Unit("Pound-force")
Rotation_per_Second_per_Second_per_Second = Unit("Rotation per Second per Second per Second")
Volt_per_Meter_per_Second = Unit("Volt per Meter per Second")
