package frc.robot.util.ts;

import com.google.gson.FieldNamingStrategy;
import coppercore.parameter_tools.json.JSONSyncConfig;
import coppercore.parameter_tools.json.JSONSyncConfigBuilder;
import coppercore.parameter_tools.json.adapters.measure.JSONMeasure;
import coppercore.parameter_tools.json.annotations.JSONExclude;
import coppercore.parameter_tools.json.annotations.JsonSubtype;
import coppercore.parameter_tools.json.annotations.JsonType;
import coppercore.parameter_tools.json.helpers.JSONConverter;
import coppercore.parameter_tools.json.helpers.JSONConverter.ConversionException;
import coppercore.parameter_tools.json.helpers.JSONObject;
import edu.wpi.first.units.Measure;
import edu.wpi.first.units.PerUnit;
import edu.wpi.first.units.Unit;
import edu.wpi.first.wpilibj.Filesystem;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.reflect.*;
import java.nio.file.Path;
import java.util.*;

/**
 * Generates Python dataclass definitions from any Java class using the same config rules as
 * JSONSync / JSONHandler. Parallel to TypeScriptGenerator but outputs Python.
 */
public final class PythonGenerator {

  private static final JSONSyncConfig defaultConfig = new JSONSyncConfigBuilder().build();

  private static FieldNamingStrategy namingStrategy;

  private static final Map<Class<?>, String> primitiveMap = new HashMap<>();
  private static final Map<Type, String> pythonTypeMap = new HashMap<>();
  private static final Set<Class<?>> generated = new HashSet<>();
  private static final Set<Type> defaultChecked = new HashSet<>();
  private static final Set<Type> defaultSupported = new HashSet<>();
  private static final StringBuilder output = new StringBuilder();
  private static boolean hasGeneratedUnits = false;
  private static final Path BASE_PATH =
      Filesystem.getDeployDirectory()
          .toPath()
          .resolve("../../..")
          .normalize()
          .resolve("auto_generator/src");
  // Output to auto_generator/src/
  private static String unitFilePath = "units.py";
  private static boolean hasImportedUnits = false;

  public static Set<Class<?>> emitted = new HashSet<>();

  // Track classes that need to_dict methods generated
  private static final List<String> toDictMethods = new ArrayList<>();

  // Extra methods to inject into generated classes we can't annotate (e.g. WPILib geometry classes)
  private static final Map<Class<?>, List<String>> extraMethods = new HashMap<>();

  /**
   * Register additional Python methods to be injected into the generated dataclass for a given Java
   * class. Each string is a complete method definition (indented with 4 spaces). Call this before
   * generateForClasses.
   */
  public static void registerExtraMethods(Class<?> clazz, String... methods) {
    extraMethods.computeIfAbsent(clazz, k -> new ArrayList<>()).addAll(Arrays.asList(methods));
  }

  private static boolean shouldSkipField(Field field) {
    return Modifier.isStatic(field.getModifiers())
        || Modifier.isTransient(field.getModifiers())
        || field.isAnnotationPresent(JSONExclude.class);
  }

  public static void setUnitFilePath(String path) {
    unitFilePath = path;
  }

  // ============================================
  // Units file generation
  // ============================================

  public static void generateUnitsFile(Path outputDir) {
    if (hasGeneratedUnits) return;
    hasGeneratedUnits = true;
    StringBuilder sb = new StringBuilder();
    sb.append(
        "\"\"\"\n"
            + "Auto-generated by PythonGenerator. Do not edit manually.\n"
            + "\n"
            + "Provides unit types and measure creation functions that serialize\n"
            + "to the same JSON format the Java robot code expects.\n"
            + "\"\"\"\n\n"
            + "from __future__ import annotations\n\n"
            + "from dataclasses import dataclass\n\n\n"
            + "@dataclass\n"
            + "class Measure:\n"
            + "    \"\"\"A measure with a numeric value and a unit name string.\"\"\"\n"
            + "    value: float\n"
            + "    unit: str\n\n"
            + "    def to_dict(self) -> dict:\n"
            + "        return {\"value\": self.value, \"unit\": self.unit}\n\n\n"
            + "@dataclass\n"
            + "class Unit:\n"
            + "    \"\"\"A named unit that can create Measure instances.\"\"\"\n"
            + "    name: str\n\n"
            + "    def of(self, value: float) -> Measure:\n"
            + "        return Measure(value=value, unit=self.name)\n\n\n");

    Set<Unit> units = new HashSet<>();
    HashMap<Class<?>, String> baseUnits = new HashMap<>();
    Set<String> emittedMeasureNames = new HashSet<>();
    JSONMeasure.unitMap.forEach(
        (name, unitFunc) -> {
          var measure = unitFunc.apply(1.0);
          var unit = measure.unit();
          var baseUnit = unit.getBaseUnit();
          if (baseUnit == null) return;
          Class<?> baseUnitClass = baseUnit.getClass();
          if (!baseUnits.containsKey(baseUnitClass)) {
            String measureName;
            if (baseUnit instanceof PerUnit<?, ?> perBaseUnit) {
              String numeratorName =
                  stripUnitSuffix(perBaseUnit.numerator().getBaseUnit().getClass().getSimpleName());
              String denominatorName =
                  stripUnitSuffix(
                      perBaseUnit.denominator().getBaseUnit().getClass().getSimpleName());
              measureName = numeratorName + "Per" + denominatorName;
            } else {
              measureName = stripUnitSuffix(baseUnitClass.getSimpleName());
            }
            if (emittedMeasureNames.contains(measureName)) return;
            emittedMeasureNames.add(measureName);
            // In Python, we don't need separate UnitType classes — just comments
            sb.append("# ").append(measureName).append(" unit type\n");
            pythonTypeMap.put(baseUnitClass, measureName);
            baseUnits.put(baseUnitClass, measureName);
          }
          if (units.contains(unit)) return;
          String registeredName = baseUnits.get(baseUnitClass);
          if (registeredName == null) return;
          units.add(unit);
          pythonTypeMap.put(unit.getClass(), registeredName);
          var unitName = unit.name().replace(" ", "_").replace("-", "_");
          if (unitName.equals("<?>")) unitName = "Unitless";
          sb.append(unitName).append(" = Unit(\"").append(unit.name()).append("\")\n");
        });

    System.out.println("Generated Python definitions for " + units.size() + " units.");

    try (FileWriter writer = new FileWriter(outputDir.resolve(unitFilePath).toString())) {
      writer.write(sb.toString());
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
  }

  static {
    primitiveMap.put(int.class, "int");
    primitiveMap.put(Integer.class, "int");
    primitiveMap.put(double.class, "float");
    primitiveMap.put(Double.class, "float");
    primitiveMap.put(float.class, "float");
    primitiveMap.put(Float.class, "float");
    primitiveMap.put(long.class, "int");
    primitiveMap.put(Long.class, "int");
    primitiveMap.put(short.class, "int");
    primitiveMap.put(Short.class, "int");
    primitiveMap.put(byte.class, "int");
    primitiveMap.put(Byte.class, "int");

    primitiveMap.put(boolean.class, "bool");
    primitiveMap.put(Boolean.class, "bool");

    primitiveMap.put(String.class, "str");
    primitiveMap.put(char.class, "str");
    primitiveMap.put(Character.class, "str");

    pythonTypeMap.putAll(primitiveMap);
  }

  // ============================================
  // Public Entry
  // ============================================

  private static Path outputDir;

  private static void initGenerator() {
    generated.clear();
    emitted.clear();
    output.setLength(0);
    toDictMethods.clear();
    hasImportedUnits = false;

    output.append(
        "\"\"\"\n"
            + "Auto-generated by PythonGenerator. Do not edit manually.\n"
            + "\"\"\"\n\n"
            + "from __future__ import annotations\n\n"
            + "import json\n"
            + "import math as _math\n"
            + "from dataclasses import dataclass, field\n"
            + "from typing import Any, Callable, List, Optional\n\n");

    namingStrategy = defaultConfig.namingPolicy();
  }

  private static void writeOutput(String filePath) {
    try (FileWriter writer = new FileWriter(outputDir.resolve(filePath).toString())) {
      writer.write(output.toString());
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
  }

  public static void generateForObjects(Path outputDir, String filePath, Object... roots) {
    PythonGenerator.outputDir = outputDir;
    initGenerator();

    for (Object root : roots) {
      resolveType(root.getClass());
    }

    writeOutput(filePath);
  }

  public static void generateForClasses(Path outputDir, String filePath, Class<?>... rootClasses) {
    PythonGenerator.outputDir = outputDir;
    initGenerator();

    for (Class<?> rootClass : rootClasses) {
      resolveType(rootClass);
    }

    writeOutput(filePath);
  }

  /** Convenience overload that uses the default BASE_PATH as output directory. */
  public static void generateForClasses(String filePath, Class<?>... rootClasses) {
    generateForClasses(BASE_PATH, filePath, rootClasses);
  }

  // ============================================
  // Core Generation
  // ============================================

  private static void generateType(Class<?> clazz) {
    generateType(clazz, clazz.getSimpleName());
  }

  private static void generateType(Class<?> clazz, String suggestedName) {
    if (generated.contains(clazz)) return;
    if (isPrimitive(clazz)) return;
    if (clazz.isEnum()) {
      generateEnum(clazz);
      return;
    }

    generated.add(clazz);

    if (clazz.isAnnotationPresent(JsonType.class)) {
      generateDiscriminatedUnion(clazz);
      return;
    }

    generateDataclass(clazz, suggestedName);
  }

  // ============================================
  // Dataclass generation
  // ============================================

  private record PythonField(
      String name,
      String pyName,
      String type,
      Class<?> originalType,
      boolean isOptional,
      boolean supportsDefault) {}

  /** Convert camelCase to snake_case */
  private static String toSnakeCase(String name) {
    StringBuilder sb = new StringBuilder();
    for (int i = 0; i < name.length(); i++) {
      char c = name.charAt(i);
      if (Character.isUpperCase(c)) {
        if (i > 0) sb.append('_');
        sb.append(Character.toLowerCase(c));
      } else {
        sb.append(c);
      }
    }
    return sb.toString();
  }

  public static void generateDataclass(Class<?> clazz, String suggestedName) {
    suggestedName = suggestedName != null ? suggestedName : clazz.getSimpleName();
    if (emitted.contains(clazz)) return;
    emitted.add(clazz);
    pythonTypeMap.put(clazz, suggestedName);

    StringBuilder sb = new StringBuilder();
    sb.append("\n@dataclass\n");
    sb.append("class ").append(suggestedName).append(":\n");

    ArrayList<PythonField> fields = new ArrayList<>();

    for (Field jField : clazz.getDeclaredFields()) {
      if (shouldSkipField(jField)) continue;

      Class<?> fieldType = jField.getType();
      Class<?> originalFieldType = fieldType;

      try {
        fieldType = JSONConverter.convert(fieldType);
      } catch (ConversionException ignored) {
      }

      String pyType = resolveType(jField.getGenericType(), originalFieldType.getSimpleName());
      String jsonName = namingStrategy.translateName(jField);
      String pyName = toSnakeCase(jsonName);

      boolean isOptional =
          jField.isAnnotationPresent(TypeScriptOptional.class)
              || Optional.class.isAssignableFrom(fieldType);

      boolean supportsDefault = supportsDefaultValue(originalFieldType);

      fields.add(
          new PythonField(
              jsonName, pyName, pyType, originalFieldType, isOptional, supportsDefault));
    }

    // Emit fields — fields with defaults must come after fields without
    // First: fields without defaults, then fields with defaults
    List<PythonField> noDefault = new ArrayList<>();
    List<PythonField> withDefault = new ArrayList<>();
    for (PythonField f : fields) {
      if (f.isOptional || f.supportsDefault) {
        withDefault.add(f);
      } else {
        noDefault.add(f);
      }
    }

    if (noDefault.isEmpty() && withDefault.isEmpty()) {
      sb.append("    pass\n");
    }

    for (PythonField f : noDefault) {
      sb.append("    ").append(f.pyName).append(": ");
      sb.append(f.type);
      sb.append("\n");
    }

    for (PythonField f : withDefault) {
      sb.append("    ").append(f.pyName).append(": ");
      if (f.isOptional) {
        sb.append("Optional[").append(f.type).append("]");
        sb.append(" = None");
      } else {
        sb.append(f.type);
        String defaultVal = getPythonDefaultValue(f.originalType, f.type);
        sb.append(" = ").append(defaultVal);
      }
      sb.append("\n");
    }

    // Generate __post_init__ for complex default values
    List<PythonField> needsPostInit = new ArrayList<>();
    for (PythonField f : withDefault) {
      if (!f.isOptional && isComplexType(f.originalType)) {
        needsPostInit.add(f);
      }
    }

    // Emit to_dict method
    sb.append("\n    def to_dict(self) -> dict:\n");
    if (fields.isEmpty()) {
      sb.append("        return {}\n");
    } else {
      sb.append("        d: dict = {}\n");
      for (PythonField f : fields) {
        if (f.isOptional) {
          sb.append("        if self.").append(f.pyName).append(" is not None:\n");
          sb.append("            d[\"")
              .append(f.name)
              .append("\"] = _to_dict(self.")
              .append(f.pyName)
              .append(")\n");
        } else {
          sb.append("        d[\"")
              .append(f.name)
              .append("\"] = _to_dict(self.")
              .append(f.pyName)
              .append(")\n");
        }
      }
      sb.append("        return d\n");
    }

    // Emit PythonMethod annotations
    emitPythonMethods(clazz, sb);
    emitExtraMethods(clazz, sb);

    sb.append("\n");
    output.append(sb);
    emitPythonAppends(clazz);
  }

  // ============================================
  // Polymorphism
  // ============================================

  private static void generateDiscriminatedUnion(Class<?> baseClass) {
    JsonType typeAnnotation = baseClass.getAnnotation(JsonType.class);
    String discriminator = typeAnnotation.property();

    List<String> subtypeNames = new ArrayList<>();

    pythonTypeMap.put(baseClass, baseClass.getSimpleName());

    for (JsonSubtype subtype : typeAnnotation.subtypes()) {
      Class<?> subClass = subtype.clazz();
      String name = subtype.name();

      subtypeNames.add(subClass.getSimpleName());
      generateSubtype(subClass, discriminator, name, baseClass);
    }

    // Union type alias
    output
        .append("\n")
        .append(baseClass.getSimpleName())
        .append(" = Optional[")
        .append(String.join(" | ", subtypeNames))
        .append("]\n\n");

    emitPythonAppends(baseClass);
  }

  private static void generateSubtype(
      Class<?> clazz, String discriminator, String discriminatorValue, Class<?> baseClass) {
    if (generated.contains(clazz)) return;
    generated.add(clazz);

    pythonTypeMap.put(clazz, clazz.getSimpleName());

    StringBuilder sb = new StringBuilder();

    sb.append("\n@dataclass\n");
    sb.append("class ").append(clazz.getSimpleName()).append(":\n");

    // Discriminator field
    sb.append("    ")
        .append(toSnakeCase(discriminator))
        .append(": str = field(default=\"")
        .append(discriminatorValue)
        .append("\", init=False)\n");

    ArrayList<PythonField> fields = new ArrayList<>();

    for (Field jField : getAllFields(clazz)) {
      if (shouldSkipField(jField)) continue;
      if (jField.getName().equals(discriminator)) continue;

      Class<?> fieldType = jField.getType();
      Class<?> originalFieldType = fieldType;

      try {
        fieldType = JSONConverter.convert(fieldType);
      } catch (ConversionException ignored) {
      }

      String pyType = resolveType(jField.getGenericType(), originalFieldType.getSimpleName());
      String jsonName = namingStrategy.translateName(jField);
      String pyName = toSnakeCase(jsonName);

      boolean isOptional =
          jField.isAnnotationPresent(TypeScriptOptional.class)
              || Optional.class.isAssignableFrom(fieldType);

      boolean supportsDefault = supportsDefaultValue(originalFieldType);

      fields.add(
          new PythonField(
              jsonName, pyName, pyType, originalFieldType, isOptional, supportsDefault));
    }

    // Fields without defaults first, then with defaults
    List<PythonField> noDefault = new ArrayList<>();
    List<PythonField> withDefault = new ArrayList<>();
    for (PythonField f : fields) {
      if (f.isOptional || f.supportsDefault) {
        withDefault.add(f);
      } else {
        noDefault.add(f);
      }
    }

    if (noDefault.isEmpty() && withDefault.isEmpty()) {
      // only the discriminator
    }

    for (PythonField f : noDefault) {
      sb.append("    ").append(f.pyName).append(": ");
      sb.append(f.type);
      sb.append("\n");
    }

    for (PythonField f : withDefault) {
      sb.append("    ").append(f.pyName).append(": ");
      if (f.isOptional) {
        sb.append("Optional[").append(f.type).append("]");
        sb.append(" = None");
      } else {
        sb.append(f.type);
        String defaultVal = getPythonDefaultValue(f.originalType, f.type);
        sb.append(" = ").append(defaultVal);
      }
      sb.append("\n");
    }

    // to_dict
    sb.append("\n    def to_dict(self) -> dict:\n");
    sb.append("        d: dict = {\"")
        .append(discriminator)
        .append("\": self.")
        .append(toSnakeCase(discriminator))
        .append("}\n");
    for (PythonField f : fields) {
      if (f.isOptional) {
        sb.append("        if self.").append(f.pyName).append(" is not None:\n");
        sb.append("            d[\"")
            .append(f.name)
            .append("\"] = _to_dict(self.")
            .append(f.pyName)
            .append(")\n");
      } else {
        sb.append("        d[\"")
            .append(f.name)
            .append("\"] = _to_dict(self.")
            .append(f.pyName)
            .append(")\n");
      }
    }
    sb.append("        return d\n");

    // Methods from base class and subclass
    emitPythonMethods(baseClass, sb);
    emitPythonMethods(clazz, sb);
    emitExtraMethods(baseClass, sb);
    emitExtraMethods(clazz, sb);

    sb.append("\n");
    output.append(sb);
    emitPythonAppends(clazz);
  }

  // ============================================
  // Type Resolution
  // ============================================

  private static String resolveType(Type type) {
    return resolveType(type, null);
  }

  private static String resolveType(Type type, String suggestedName) {
    if (type instanceof Class<?> clazz) {
      boolean isUnit = isUnitType(clazz);
      if (isUnit) {
        ensureUnitsIncluded();
      }

      try {
        Class<? extends JSONObject<?>> wrapper = JSONConverter.convert(clazz);
        if (wrapper != null) {
          suggestedName = clazz.getSimpleName();
          clazz = wrapper;
        }
      } catch (JSONConverter.ConversionException ignored) {
      }

      if (primitiveMap.containsKey(clazz)) {
        return primitiveMap.get(clazz);
      }

      if (clazz.isArray()) {
        return "List[" + resolveType(clazz.getComponentType()) + "]";
      }

      if (Map.class.isAssignableFrom(clazz)) {
        return "dict";
      }

      suggestedName = suggestedName != null ? suggestedName : clazz.getSimpleName();
      if (isUnit) {
        return "units.Measure";
      }
      generateType(clazz, suggestedName);
      return suggestedName;
    }

    if (type instanceof ParameterizedType pt) {
      Type raw = pt.getRawType();
      Type[] args = pt.getActualTypeArguments();
      if (raw instanceof Class<?> rawClass) {
        boolean isUnit = isUnitType(rawClass);
        if (isUnit) {
          ensureUnitsIncluded();
        }

        if (Collection.class.isAssignableFrom(rawClass)) {
          return "List[" + resolveType(args[0]) + "]";
        }

        if (Map.class.isAssignableFrom(rawClass)) {
          return "dict";
        }

        if (Optional.class.isAssignableFrom(rawClass)) {
          return "Optional[" + resolveType(args[0]) + "]";
        }

        try {
          Class<? extends JSONObject<?>> wrapper = JSONConverter.convert(rawClass);
          if (wrapper != null) {
            suggestedName = rawClass.getSimpleName();
            rawClass = wrapper;
          }
        } catch (JSONConverter.ConversionException ignored) {
        }

        if (isUnitType(rawClass)) {
          isUnit = true;
          ensureUnitsIncluded();
        }

        suggestedName = suggestedName != null ? suggestedName : rawClass.getSimpleName();
        generateType(rawClass, suggestedName);
        if (isUnit) {
          return "units.Measure";
        }
        return suggestedName;
      }
    }

    return "Any";
  }

  // ============================================
  // Enums
  // ============================================

  private static void generateEnum(Class<?> clazz) {
    if (generated.contains(clazz)) return;
    generated.add(clazz);
    pythonTypeMap.put(clazz, clazz.getSimpleName());

    Object[] constants = clazz.getEnumConstants();
    List<String> values = new ArrayList<>();
    for (Object constant : constants) {
      values.add("\"" + constant.toString() + "\"");
    }

    output
        .append("\n")
        .append(clazz.getSimpleName())
        .append(" = str  # Literal[")
        .append(String.join(", ", values))
        .append("]\n\n");
  }

  // ============================================
  // Python-specific code injection
  // ============================================

  private static void emitPythonMethods(Class<?> clazz, StringBuilder sb) {
    PythonMethod[] methods = clazz.getAnnotationsByType(PythonMethod.class);
    for (PythonMethod method : methods) {
      sb.append("\n");
      if (!method.comment().isEmpty()) {
        // Emit as docstring inside the method
      }
      sb.append("    ");
      if (method.isStatic()) {
        sb.append("@staticmethod\n    ");
      }
      sb.append("def ").append(method.name()).append("(");
      if (!method.isStatic()) {
        sb.append("self");
      }
      sb.append(")");
      if (!method.returnType().equals("None") && !method.returnType().equals("self")) {
        sb.append(" -> ").append(method.returnType());
      }
      sb.append(":\n");
      if (!method.comment().isEmpty()) {
        sb.append("        \"\"\"").append(method.comment()).append("\"\"\"\n");
      }
      for (String line : method.body()) {
        sb.append("        ").append(line).append("\n");
      }
    }
  }

  private static void emitExtraMethods(Class<?> clazz, StringBuilder sb) {
    List<String> methods = extraMethods.get(clazz);
    if (methods == null) return;
    for (String methodCode : methods) {
      sb.append("\n");
      // Each methodCode string is already indented with 4-space class-level indent
      sb.append(methodCode).append("\n");
    }
  }

  private static void emitPythonAppends(Class<?> clazz) {
    PythonAppend[] appends = clazz.getAnnotationsByType(PythonAppend.class);
    for (PythonAppend append : appends) {
      if (append.atTop()) {
        // Insert after the initial imports block
        int insertPos = output.indexOf("from typing import");
        if (insertPos >= 0) {
          insertPos = output.indexOf("\n", insertPos) + 1;
          output.insert(insertPos, append.value() + "\n");
        } else {
          output.insert(0, append.value() + "\n");
        }
      } else {
        output.append(append.value()).append("\n");
      }
    }
  }

  // ============================================
  // Utilities
  // ============================================

  private static String stripUnitSuffix(String name) {
    return name.endsWith("Unit") ? name.substring(0, name.length() - 4) : name;
  }

  private static boolean isPrimitive(Class<?> clazz) {
    return clazz.isPrimitive() || primitiveMap.containsKey(clazz);
  }

  private static List<Field> getAllFields(Class<?> clazz) {
    List<Field> fields = new ArrayList<>();
    while (clazz != null) {
      fields.addAll(Arrays.asList(clazz.getDeclaredFields()));
      clazz = clazz.getSuperclass();
    }
    return fields;
  }

  private static boolean isUnitType(Class<?> clazz) {
    return Measure.class.isAssignableFrom(clazz) || Unit.class.isAssignableFrom(clazz);
  }

  private static boolean isComplexType(Class<?> type) {
    return !isPrimitive(type) && !type.isEnum() && !isUnitType(type);
  }

  private static boolean supportsDefaultValue(Type type) {
    if (!defaultChecked.contains(type)) {
      getPythonDefaultValue(type, "");
    }
    return defaultSupported.contains(type);
  }

  private static String getPythonDefaultValue(Type type, String pyTypeName) {
    if (type instanceof Class<?> clazz) {
      if (primitiveMap.containsKey(clazz)) {
        String pyType = primitiveMap.get(clazz);
        switch (pyType) {
          case "int":
            return "0";
          case "float":
            return "0.0";
          case "bool":
            return "False";
          case "str":
            return "\"\"";
          default:
            return "None";
        }
      }

      if (clazz.isArray() || Collection.class.isAssignableFrom(clazz)) {
        defaultChecked.add(type);
        defaultSupported.add(type);
        return "field(default_factory=list)";
      }

      if (clazz.isEnum()) {
        Object[] constants = clazz.getEnumConstants();
        if (constants.length > 0) {
          defaultChecked.add(type);
          defaultSupported.add(type);
          return "\"" + constants[0].toString() + "\"";
        }
      }

      if (Modifier.isAbstract(clazz.getModifiers())) {
        defaultChecked.add(type);
        defaultSupported.add(type);
        return "None";
      }

      if (isUnitType(clazz)) {
        defaultChecked.add(type);
        defaultSupported.add(type);
        return "None";
      }

      try {
        var wrapper = JSONConverter.convert(clazz);
        if (wrapper != null) {
          String wrapperName = pythonTypeMap.getOrDefault(clazz, clazz.getSimpleName());
          defaultChecked.add(type);
          defaultSupported.add(type);
          return "field(default_factory=" + wrapperName + ")";
        }
      } catch (ConversionException ignored) {
      }

      // Check if all sub-fields support defaults
      for (Field field : getAllFields(clazz)) {
        if (shouldSkipField(field)) continue;
        if (field.isAnnotationPresent(TypeScriptOptional.class)) continue;
        if (!supportsDefaultValue(field.getType())) {
          defaultChecked.add(type);
          return "None";
        }
      }

      defaultChecked.add(type);
      defaultSupported.add(type);
      String className = pythonTypeMap.getOrDefault(clazz, clazz.getSimpleName());
      return "field(default_factory=" + className + ")";
    }

    if (type instanceof ParameterizedType pt) {
      Type raw = pt.getRawType();
      if (raw instanceof Class<?> rawClass) {
        if (Collection.class.isAssignableFrom(rawClass)) {
          defaultChecked.add(type);
          defaultSupported.add(type);
          return "field(default_factory=list)";
        }
        if (Map.class.isAssignableFrom(rawClass)) {
          defaultChecked.add(type);
          defaultSupported.add(type);
          return "field(default_factory=dict)";
        }
        if (Optional.class.isAssignableFrom(rawClass)) {
          defaultChecked.add(type);
          defaultSupported.add(type);
          return "None";
        }
      }
    }

    defaultChecked.add(type);
    defaultSupported.add(type);
    return "None";
  }

  private static void ensureUnitsIncluded() {
    if (!hasGeneratedUnits) {
      generateUnitsFile(outputDir);
    }
    if (hasImportedUnits) return;
    hasImportedUnits = true;
    output.append("from . import units\n\n");
  }
}
