package frc.robot.util.ts;

import com.google.gson.FieldNamingStrategy;
import coppercore.parameter_tools.json.JSONSyncConfig;
import coppercore.parameter_tools.json.JSONSyncConfigBuilder;
import coppercore.parameter_tools.json.adapters.measure.JSONMeasure;
import coppercore.parameter_tools.json.annotations.JSONExclude;
import coppercore.parameter_tools.json.annotations.JsonSubtype;
import coppercore.parameter_tools.json.annotations.JsonType;
import coppercore.parameter_tools.json.helpers.JSONConverter;
import coppercore.parameter_tools.json.helpers.JSONConverter.ConversionException;
import coppercore.parameter_tools.json.helpers.JSONObject;
import coppercore.parameter_tools.json.strategies.JSONNamingStrategy;
import coppercore.parameter_tools.json.strategies.JSONPrimitiveCheckStrategy;
import edu.wpi.first.units.Measure;
import edu.wpi.first.units.PerUnit;
import edu.wpi.first.units.Unit;
import edu.wpi.first.wpilibj.Filesystem;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.reflect.*;
import java.nio.file.Path;
import java.util.*;

// Written with the help of ChatGPT.
// Written with help of Copilot (Claude model)
// Many changes done by hand.

/**
 * Generates TypeScript definitions from any Java class using the same config rules as JSONSync /
 * JSONHandler.
 */
public final class TypeScriptGenerator {

  private static final JSONSyncConfig defaultConfig = new JSONSyncConfigBuilder().build();

  private static FieldNamingStrategy namingStrategy;

  private static final Map<Class<?>, String> primitiveMap = new HashMap<>();
  private static final Map<Type, String> typeScriptTypeMap = new HashMap<>();
  private static final Set<Class<?>> generated = new HashSet<>();
  private static final Set<Type> defaultChecked = new HashSet<>(primitiveMap.keySet());
  private static final Set<Type> defaultSupported = new HashSet<>(primitiveMap.keySet());
  private static final StringBuilder output = new StringBuilder();
  private static boolean hasGeneratedUnits = false;
  private static final String BASE_FILE_PATH = "typescript";
  private static final Path BASE_PATH =
      Filesystem.getDeployDirectory().toPath().resolve(BASE_FILE_PATH);
  private static String unitFilePath = "Units.ts";
  private static boolean hasImportedUnits = false;

  public static Set<Class<?>> emitted = new HashSet<>();

  private static final boolean shouldSkipField(Field field) {
    return Modifier.isStatic(field.getModifiers())
        || Modifier.isTransient(field.getModifiers())
        || field.isAnnotationPresent(JSONExclude.class);
  }

  public static void setUnitFilePath(String path) {
    unitFilePath = path;
  }

  public static void generateUnitsFile() {
    if (hasGeneratedUnits) return;
    hasGeneratedUnits = true;
    StringBuilder sb = new StringBuilder();
    sb.append("// This file is auto-generated by TypeScriptGenerator. Do not edit manually.\n\n");
    sb.append(
        "class UnitType<UnitTypeName extends string> {\r\n"
            + //
            "\tconstructor(public name: UnitTypeName) {}\r\n"
            + //
            "}\n\n");
    sb.append(
        "export type Measure<MUnitType extends UnitType<any>> = {\r\n"
            + //
            "\tvalue: number;\r\n"
            + //
            "\tunit: string;\r\n"
            + //
            "\t_unitType?: MUnitType;\r\n"
            + //
            "} | null | undefined;\n\n");
    sb.append(
        "export class Unit<UUnitType extends UnitType<any>>{\r\n"
            + //
            "\tconstructor(public name: string, public unitType: UUnitType) {}\r\n"
            + //
            "\tof(value: number): Measure<UUnitType> {\r\n"
            + //
            "\t\treturn { value, unit: this.name, _unitType: this.unitType } as Measure<UUnitType>;\r\n"
            + //
            "\t}\r\n"
            + //
            "}\n\n");

    Set<Unit> units = new HashSet<>();
    HashMap<Class<?>, String> baseUnits = new HashMap<>();
    Set<String> emittedMeasureNames = new HashSet<>();
    JSONMeasure.unitMap.forEach(
        (name, unitFunc) -> {
          var measure = unitFunc.apply(1.0);
          var unit = measure.unit();
          var baseUnit = unit.getBaseUnit();
          if (baseUnit == null) return;
          Class<?> baseUnitClass = baseUnit.getClass();
          if (!baseUnits.containsKey(baseUnitClass)) {
            String measureName;
            if (baseUnit instanceof PerUnit<?, ?> perBaseUnit) {
              // For PerUnit (and its subclasses like VelocityUnit), derive a unique name
              // from the numerator and denominator unit types, e.g. VelocityUnit<CurrentUnit>
              // → "CurrentPerTime", PerUnit<VoltageUnit, AngularVelocityUnit> →
              // "VoltagePerAngularVelocity".
              // Named subclasses like LinearVelocityUnit, AngularAccelerationUnit etc. have
              // a descriptive getSimpleName() and are handled by the else branch below.
              String numeratorName =
                  stripUnitSuffix(perBaseUnit.numerator().getBaseUnit().getClass().getSimpleName());
              String denominatorName =
                  stripUnitSuffix(
                      perBaseUnit.denominator().getBaseUnit().getClass().getSimpleName());
              measureName = numeratorName + "Per" + denominatorName;
            } else {
              measureName = stripUnitSuffix(baseUnitClass.getSimpleName());
            }
            // Skip if a type with this name was already emitted (collision guard)
            if (emittedMeasureNames.contains(measureName)) return;
            emittedMeasureNames.add(measureName);
            sb.append("export class ")
                .append(measureName)
                .append("_UnitType")
                .append(" extends UnitType<\"")
                .append(measureName)
                .append("\"> {}\n");
            sb.append("export type ")
                .append(measureName)
                .append(" = ")
                .append(" Measure<")
                .append(measureName)
                .append("_UnitType>;\n");
            typeScriptTypeMap.put(baseUnitClass, measureName);
            baseUnits.put(baseUnitClass, measureName);
          }
          if (units.contains(unit)) return;
          // Skip units whose base class was not registered (filtered above)
          String registeredName = baseUnits.get(baseUnitClass);
          if (registeredName == null) return;
          units.add(unit);
          typeScriptTypeMap.put(unit.getClass(), registeredName);
          var unitName = unit.name().replace(" ", "_").replace("-", "_");
          if (unitName.equals("<?>")) unitName = "Unitless";
          sb.append("export const ")
              .append(unitName)
              .append(" = new Unit<")
              .append(registeredName)
              .append("_UnitType>(\"")
              .append(unit.name())
              .append("\", new ")
              .append(registeredName)
              .append("_UnitType(\"")
              .append(registeredName)
              .append("\"));\n");
        });

    System.out.println("Generated TypeScript definitions for " + units.size() + " units.");

    try (FileWriter writer = new FileWriter(BASE_PATH.resolve(unitFilePath).toString())) {
      writer.write(sb.toString());
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
  }

  static {
    primitiveMap.put(int.class, "number");
    primitiveMap.put(Integer.class, "number");
    primitiveMap.put(double.class, "number");
    primitiveMap.put(Double.class, "number");
    primitiveMap.put(float.class, "number");
    primitiveMap.put(Float.class, "number");
    primitiveMap.put(long.class, "number");
    primitiveMap.put(Long.class, "number");
    primitiveMap.put(short.class, "number");
    primitiveMap.put(Short.class, "number");
    primitiveMap.put(byte.class, "number");
    primitiveMap.put(Byte.class, "number");

    primitiveMap.put(boolean.class, "boolean");
    primitiveMap.put(Boolean.class, "boolean");

    primitiveMap.put(String.class, "string");
    primitiveMap.put(char.class, "string");
    primitiveMap.put(Character.class, "string");

    typeScriptTypeMap.putAll(primitiveMap);
  }

  // ============================================
  // Public Entry
  // ============================================

  private static void initGenerator() {
    generated.clear();
    emitted.clear();
    output.setLength(0);
    hasImportedUnits = false;

    output.append(
        "// This file is auto-generated by TypeScriptGenerator. Do not edit manually.\n\n");

    namingStrategy =
        JSONPrimitiveCheckStrategy.checkForPrimitives(
            new JSONNamingStrategy(defaultConfig.namingPolicy(), defaultConfig), defaultConfig);
  }

  private static void writeOutput(String filePath) {
    try (FileWriter writer = new FileWriter(BASE_PATH.resolve(filePath).toString())) {
      writer.write(output.toString());
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
  }

  public static void generateForObjects(String filePath, Object... roots) {
    initGenerator();

    for (Object root : roots) {
      generateType(root.getClass());
    }

    writeOutput(filePath);
  }

  public static void generateForClasses(String filePath, Class<?>... rootClasses) {
    initGenerator();

    for (Class<?> rootClass : rootClasses) {
      generateType(rootClass);
    }

    writeOutput(filePath);
  }

  // ============================================
  // Core Generation
  // ============================================

  private static void generateType(Class<?> clazz) {
    generateType(clazz, clazz.getSimpleName());
  }

  private static void generateType(Class<?> clazz, String suggestedName) {

    if (generated.contains(clazz)) return;
    if (isPrimitive(clazz)) return;
    if (clazz.isEnum()) {
      generateEnum(clazz);
      return;
    }

    generated.add(clazz);

    // Handle polymorphic types
    if (clazz.isAnnotationPresent(JsonType.class)) {
      generateDiscriminatedUnion(clazz);
      return;
    }

    generateInterface(clazz, suggestedName);
  }

  // ============================================
  // Interfaces
  // ============================================

  private record TypeScriptField(
      String name, String type, Class<?> originalType, boolean isTypeScriptOptional) {}

  public static void generateInterface(Class<?> clazz, String suggestedName) {
    suggestedName = suggestedName != null ? suggestedName : clazz.getSimpleName();
    if (emitted.contains(clazz)) return;
    emitted.add(clazz);
    typeScriptTypeMap.put(clazz, suggestedName);

    StringBuilder sb = new StringBuilder();
    sb.append("export class ").append(suggestedName).append(" {\n");

    ArrayList<TypeScriptField> fields = new ArrayList<>();

    for (Field field : clazz.getDeclaredFields()) {
      if (shouldSkipField(field)) continue;

      Class<?> fieldType = field.getType();
      Class<?> originalFieldType = fieldType;

      // Use JSONConverter if available
      try {
        fieldType = JSONConverter.convert(fieldType);
      } catch (ConversionException ignored) {
      }

      String tsType = resolveType(field.getGenericType(), originalFieldType.getSimpleName());

      String name = namingStrategy.translateName(field);

      boolean isOptional = field.isAnnotationPresent(TypeScriptOptional.class);
      isOptional = isOptional || Optional.class.isAssignableFrom(fieldType);

      fields.add(new TypeScriptField(name, tsType, originalFieldType, isOptional));
    }

    boolean supportsDefault = supportsDefaultValue(clazz);

    for (TypeScriptField field : fields) {
      sb.append("  ").append(field.name);
      if (supportsDefault) {
        sb.append("?");
      }
      sb.append(": ").append(field.type);
      if (field.isTypeScriptOptional) {
        sb.append(" | undefined");
      }
      sb.append(";\n");
    }

    sb.append("\tconstructor({");

    for (int i = 0; i < fields.size(); i++) {
      TypeScriptField field = fields.get(i);
      sb.append(field.name);
      if (supportsDefault) {
        String defaultValue = getDefaultValue(field.originalType);
        if (field.isTypeScriptOptional) {
          defaultValue = "undefined";
        }
        ;
        sb.append(" = ").append(defaultValue);
      }
      if (i < fields.size() - 1) {
        sb.append(", ");
      }
    }

    sb.append("}: ");

    if (supportsDefault) {
      sb.append("Partial<");
    }

    sb.append("{");

    for (int i = 0; i < fields.size(); i++) {
      TypeScriptField field = fields.get(i);
      sb.append(field.name).append(": ").append(field.type);
      if (i < fields.size() - 1) {
        sb.append("; ");
      }
    }

    sb.append("}");

    if (supportsDefault) {
      sb.append(">");
    }

    sb.append(") {\n");

    for (TypeScriptField field : fields) {
      sb.append("    this.").append(field.name).append(" = ").append(field.name).append(";\n");
    }

    sb.append("  }\n");

    emitTypeScriptMethods(clazz, sb);

    sb.append("}\n\n");
    output.append(sb);
    emitTypeScriptImports(clazz);
    emitTypeScriptAppends(clazz);
  }

  // ============================================
  // Polymorphism
  // ============================================

  private static void generateDiscriminatedUnion(Class<?> baseClass) {

    JsonType typeAnnotation = baseClass.getAnnotation(JsonType.class);
    String discriminator = typeAnnotation.property();

    List<String> subtypeNames = new ArrayList<>();

    typeScriptTypeMap.put(baseClass, baseClass.getSimpleName());

    for (JsonSubtype subtype : typeAnnotation.subtypes()) {
      Class<?> subClass = subtype.clazz();
      String name = subtype.name();

      subtypeNames.add(subClass.getSimpleName());

      generateSubtype(subClass, discriminator, name, baseClass);
    }

    output
        .append("export type ")
        .append(baseClass.getSimpleName())
        .append(" = ")
        .append(String.join(" | ", subtypeNames))
        .append(
            " | undefined | null") // Allow null and undefined for polymorphic types objects in java
        // can be null and need to support optional properties for
        // subtypes that have additional fields
        .append(";\n\n");

    // Emit custom code for the base class (imports, appends)
    emitTypeScriptImports(baseClass);
    emitTypeScriptAppends(baseClass);
  }

  private static void generateSubtype(
      Class<?> clazz, String discriminator, String discriminatorValue, Class<?> baseClass) {

    if (generated.contains(clazz)) return;
    generated.add(clazz);

    typeScriptTypeMap.put(clazz, clazz.getSimpleName());

    StringBuilder sb = new StringBuilder();

    sb.append("export class ").append(clazz.getSimpleName()).append(" {\n");
    sb.append("  ")
        .append(discriminator)
        .append(": \"")
        .append(discriminatorValue)
        .append("\" = \"")
        .append(discriminatorValue)
        .append("\";\n");

    ArrayList<TypeScriptField> fields = new ArrayList<>();

    for (Field field : getAllFields(clazz)) {
      if (shouldSkipField(field)) continue;
      if (field.getName().equals(discriminator)) continue;

      Class<?> fieldType = field.getType();
      Class<?> originalFieldType = fieldType;

      try {
        fieldType = JSONConverter.convert(fieldType);
      } catch (ConversionException ignored) {
      }

      String tsType = resolveType(field.getGenericType(), originalFieldType.getSimpleName());
      String name = namingStrategy.translateName(field);

      boolean isOptional = field.isAnnotationPresent(TypeScriptOptional.class);
      isOptional = isOptional || Optional.class.isAssignableFrom(fieldType);

      fields.add(new TypeScriptField(name, tsType, originalFieldType, isOptional));
    }

    boolean supportsDefault = supportsDefaultValue(clazz);

    for (TypeScriptField field : fields) {
      sb.append("  ").append(field.name);
      if (supportsDefault) {
        sb.append("?");
      }
      sb.append(": ").append(field.type);
      if (field.isTypeScriptOptional) {
        sb.append(" | undefined");
      }
      sb.append(";\n");
    }

    sb.append("\tconstructor({");

    for (int i = 0; i < fields.size(); i++) {
      TypeScriptField field = fields.get(i);
      sb.append(field.name);
      if (supportsDefault) {
        String defaultValue = getDefaultValue(field.originalType);
        if (field.isTypeScriptOptional) {
          defaultValue = "undefined";
        }
        sb.append(" = ").append(defaultValue);
      }
      if (i < fields.size() - 1) {
        sb.append(", ");
      }
    }

    sb.append("}: ");

    if (supportsDefault) {
      sb.append("Partial<");
    }

    sb.append("{");

    for (int i = 0; i < fields.size(); i++) {
      TypeScriptField field = fields.get(i);
      sb.append(field.name).append(": ").append(field.type);
      if (i < fields.size() - 1) {
        sb.append("; ");
      }
    }

    sb.append("}");

    if (supportsDefault) {
      sb.append(">");
    }

    sb.append(") {\n");

    for (TypeScriptField field : fields) {
      sb.append("    this.").append(field.name).append(" = ").append(field.name).append(";\n");
    }

    sb.append("  }\n");

    // Emit methods from both the base class and the subclass itself
    emitTypeScriptMethods(baseClass, sb);
    emitTypeScriptMethods(clazz, sb);

    sb.append("}\n\n");
    output.append(sb);
    emitTypeScriptImports(clazz);
    emitTypeScriptAppends(clazz);
  }

  // ============================================
  // Type Resolution
  // ============================================

  private static String resolveType(Type type) {
    return resolveType(type, null);
  }

  private static String resolveType(Type type, String suggestedName) {
    if (type instanceof Class<?> clazz) {

      boolean isUnit = isUnitType(clazz);
      if (isUnit) {
        ensureUnitsIncluded();
      }

      // Check if class has a JSON wrapper
      try {
        Class<? extends JSONObject<?>> wrapper = JSONConverter.convert(clazz);
        if (wrapper != null) {
          suggestedName = clazz.getSimpleName();
          clazz = wrapper; // Use the wrapper for generating TypeScript
        }
      } catch (JSONConverter.ConversionException ignored) {
        // No wrapper, continue as normal
      }

      if (primitiveMap.containsKey(clazz)) {
        return primitiveMap.get(clazz);
      }

      if (clazz.isArray()) {
        return resolveType(clazz.getComponentType()) + "[]";
      }

      if (Map.class.isAssignableFrom(clazz)) {
        return "{ [key: string]: any }";
      }

      suggestedName = suggestedName != null ? suggestedName : clazz.getSimpleName();
      if (isUnit) {
        // For units, we want to return the Measure type instead of the wrapper interface
        // Maybe still call generateType in case of Per Units
        return "Units." + suggestedName;
      }
      generateType(clazz, suggestedName);
      return suggestedName;
    }

    if (type instanceof ParameterizedType pt) {
      Type raw = pt.getRawType();
      Type[] args = pt.getActualTypeArguments();
      if (raw instanceof Class<?> rawClass) {

        boolean isUnit = isUnitType(rawClass);

        if (isUnit) {
          ensureUnitsIncluded();
        }

        // List<T>
        if (Collection.class.isAssignableFrom(rawClass)) {
          return resolveType(args[0]) + "[]";
        }

        // Map<String, T>
        if (Map.class.isAssignableFrom(rawClass)) {
          return "{ [key: string]: " + resolveType(args[1]) + " }";
        }

        if (Optional.class.isAssignableFrom(rawClass)) {
          return "Partial<" + resolveType(args[0]) + ">";
        }

        // Check wrapper for raw class
        try {
          Class<? extends JSONObject<?>> wrapper = JSONConverter.convert(rawClass);
          if (wrapper != null) {
            suggestedName = rawClass.getSimpleName();
            rawClass = wrapper;
          }
        } catch (JSONConverter.ConversionException ignored) {
        }

        if (isUnitType(rawClass)) {
          isUnit = true;
          ensureUnitsIncluded();
        }

        suggestedName = suggestedName != null ? suggestedName : rawClass.getSimpleName();
        generateType(rawClass, suggestedName);
        if (isUnit) {
          // For units, we want to return the Measure type instead of the wrapper interface
          return "Units." + suggestedName;
        }
        return suggestedName;
      }
    }

    return "any";
  }

  // ============================================
  // Enums
  // ============================================

  private static void generateEnum(Class<?> clazz) {

    if (generated.contains(clazz)) return;
    generated.add(clazz);
    typeScriptTypeMap.put(clazz, clazz.getSimpleName());

    output.append("export type ").append(clazz.getSimpleName()).append(" = ");

    Object[] constants = clazz.getEnumConstants();
    List<String> values = new ArrayList<>();

    for (Object constant : constants) {
      values.add("\"" + constant.toString() + "\"");
    }

    output.append(String.join(" | ", values)).append(";\n\n");
  }

  // ============================================
  // Custom TypeScript Code Injection
  // ============================================

  /**
   * Emits any @TypeScriptMethod-annotated method bodies into the class StringBuilder, before the
   * closing brace. Assembles valid TypeScript method syntax from the structured annotation fields.
   */
  private static void emitTypeScriptMethods(Class<?> clazz, StringBuilder sb) {
    TypeScriptMethod[] methods = clazz.getAnnotationsByType(TypeScriptMethod.class);
    for (TypeScriptMethod method : methods) {
      // JSDoc comment
      if (!method.comment().isEmpty()) {
        sb.append("  /** ").append(method.comment()).append(" */\n");
      }
      // Method signature
      sb.append("  ");
      if (method.isStatic()) {
        sb.append("static ");
      }
      sb.append(method.name()).append("(");
      TypeScriptParam[] params = method.params();
      for (int i = 0; i < params.length; i++) {
        sb.append(params[i].name());
        if (params[i].optional()) {
          sb.append("?");
        }
        sb.append(": ").append(params[i].type());
        if (i < params.length - 1) {
          sb.append(", ");
        }
      }
      sb.append("): ").append(method.returnType()).append(" {\n");
      // Body
      for (String line : method.body()) {
        sb.append("    ").append(line).append("\n");
      }
      sb.append("  }\n");
    }
  }

  /**
   * Emits any @TypeScriptImport-annotated import statements at the top of the output. Supports
   * namespace imports ({@code import * as X from '...'}) and named imports ({@code import { a, b }
   * from '...'}).
   */
  private static void emitTypeScriptImports(Class<?> clazz) {
    TypeScriptImport[] imports = clazz.getAnnotationsByType(TypeScriptImport.class);
    for (TypeScriptImport imp : imports) {
      StringBuilder sb = new StringBuilder();
      if (!imp.alias().isEmpty()) {
        sb.append("import * as ")
            .append(imp.alias())
            .append(" from '")
            .append(imp.module())
            .append("';\n");
      } else if (imp.members().length > 0) {
        sb.append("import { ")
            .append(String.join(", ", imp.members()))
            .append(" } from '")
            .append(imp.module())
            .append("';\n");
      }
      output.insert(0, sb.toString());
    }
  }

  /**
   * Emits any @TypeScriptAppend-annotated code blocks. Code marked atTop=true is prepended to
   * output; otherwise it is appended after the class.
   */
  private static void emitTypeScriptAppends(Class<?> clazz) {
    TypeScriptAppend[] appends = clazz.getAnnotationsByType(TypeScriptAppend.class);
    for (TypeScriptAppend append : appends) {
      if (append.atTop()) {
        output.insert(0, append.value() + "\n");
      } else {
        output.append(append.value()).append("\n");
      }
    }
  }

  // ============================================
  // Utilities
  // ============================================

  /**
   * Removes a trailing "Unit" suffix from a unit class simple name, e.g. "DistanceUnit" →
   * "Distance".
   */
  private static String stripUnitSuffix(String name) {
    return name.endsWith("Unit") ? name.substring(0, name.length() - 4) : name;
  }

  private static boolean isPrimitive(Class<?> clazz) {
    return clazz.isPrimitive() || primitiveMap.containsKey(clazz);
  }

  private static List<Field> getAllFields(Class<?> clazz) {
    List<Field> fields = new ArrayList<>();
    while (clazz != null) {
      fields.addAll(Arrays.asList(clazz.getDeclaredFields()));
      clazz = clazz.getSuperclass();
    }
    return fields;
  }

  private static boolean isUnitType(Class<?> clazz) {
    return Measure.class.isAssignableFrom(clazz) || Unit.class.isAssignableFrom(clazz);
  }

  private static void ensureUnitsFile() {
    if (hasGeneratedUnits) return;
    generateUnitsFile();
  }

  private static boolean supportsDefaultValue(Type type) {
    if (!defaultChecked.contains(type)) {
      getDefaultValue(type); // This will populate defaultChecked and defaultSupported
    }
    return defaultSupported.contains(type);
  }

  private static String getDefaultValue(Type type) {
    Optional<String> defaultValue = _getDefaultValue(type);
    if (!defaultChecked.contains(type)) {
      defaultChecked.add(type);
      if (defaultValue != null) {
        defaultSupported.add(type);
      }
    }
    defaultValue = defaultValue != null ? defaultValue : Optional.empty();
    return defaultValue.orElse("undefined");
  }

  // Is using the fact I can return null to distinguish between should default to null, and should
  // not have a default value at all. A bit hacky but it works.
  private static Optional<String> _getDefaultValue(Type type) {
    if (defaultChecked.contains(type) && !defaultSupported.contains(type)) {
      return null;
    }
    if (primitiveMap.containsKey(type)) {
      String tsType = primitiveMap.get(type);
      switch (tsType) {
        case "number":
          return Optional.of("0");
        case "boolean":
          return Optional.of("false");
        case "string":
          return Optional.of("\"\"");
        default:
          return Optional.of("undefined");
      }
    }

    if (type instanceof Class<?> clazz) {

      if (clazz.isArray()) {
        return Optional.of("[]");
      }

      if (clazz.isEnum()) {
        Object[] constants = clazz.getEnumConstants();
        if (constants.length > 0) {
          return Optional.of("\"" + constants[0].toString() + "\"");
        }
      }

      if (Modifier.isAbstract(clazz.getModifiers())) {
        return Optional.of("undefined");
      }

      if (isUnitType(clazz)) {
        ensureUnitsIncluded();
        return Optional.of(
            "null"); // Units don't have a reasonable default value, so we should just default to
        // null
      }

      try {
        var wrapper = JSONConverter.convert(clazz);
        if (wrapper != null) {
          return Optional.of(getDefaultValue(wrapper));
        }
      } catch (ConversionException e) {
      }

      // Test if all sub fields can have default values, if so we can default to an object with all
      // default values.
      // This is a bit of a stretch but it allows us to have reasonable defaults for simple data
      // classes without
      // having to write custom TypeAdapters or default value providers.
      for (Field field : getAllFields(clazz)) {
        if (shouldSkipField(field)) continue;
        if (field.isAnnotationPresent(TypeScriptOptional.class)) continue;
        if (!supportsDefaultValue(field.getType())) {
          return null;
        }
      }

      // If we got here, it means all fields support default values, so we can return an object with
      // all default values.
      // So we should just be able to call a empty constructor
      return Optional.of("new " + typeScriptTypeMap.get(clazz) + "({})");
    }

    if (type instanceof ParameterizedType pt) {
      Type raw = pt.getRawType();
      if (raw instanceof Class<?> rawClass) {
        if (Collection.class.isAssignableFrom(rawClass)) {
          return Optional.of("[]");
        }
        if (Map.class.isAssignableFrom(rawClass)) {
          return Optional.of("{}");
        }
        if (Optional.class.isAssignableFrom(rawClass)) {
          return Optional.of("undefined");
        }
      } else {
        return Optional.of(getDefaultValue(raw));
      }
    }

    return null;
  }

  private static void ensureUnitsIncluded() {
    ensureUnitsFile();
    if (hasImportedUnits) return;
    hasImportedUnits = true;
    // TODO: add import statement to the output for the units file if it hasn't been added already
    output
        .append("import * as Units from './")
        .append(unitFilePath.replace(".ts", ".js"))
        .append("';\n\n");
  }
}
