// This file is auto-generated by TypeScriptGenerator. Do not edit manually.

export class Deadline {
  type: "Deadline" = "Deadline";
  deadline?: AutoAction;
  others?: AutoAction[];
	constructor({deadline = undefined, others = []}: Partial<{deadline: AutoAction; others: AutoAction[]}>) {
    this.deadline = deadline;
    this.others = others;
  }
  /** Adds this command to the current auto and returns itself for chaining. */
  add(): this {
    _addCommandHook?.(this);
    return this;
  }
}

export class Sequence {
  type: "Sequence" = "Sequence";
  actions?: AutoAction[];
	constructor({actions = []}: Partial<{actions: AutoAction[]}>) {
    this.actions = actions;
  }
  /** Adds this command to the current auto and returns itself for chaining. */
  add(): this {
    _addCommandHook?.(this);
    return this;
  }
}

export class Parallel {
  type: "Parallel" = "Parallel";
  actions?: AutoAction[];
	constructor({actions = []}: Partial<{actions: AutoAction[]}>) {
    this.actions = actions;
  }
  /** Adds this command to the current auto and returns itself for chaining. */
  add(): this {
    _addCommandHook?.(this);
    return this;
  }
}

export class Race {
  type: "Race" = "Race";
  actions?: AutoAction[];
	constructor({actions = []}: Partial<{actions: AutoAction[]}>) {
    this.actions = actions;
  }
  /** Adds this command to the current auto and returns itself for chaining. */
  add(): this {
    _addCommandHook?.(this);
    return this;
  }
}

import * as Units from './Units.js';

export class Wait {
  type: "Wait" = "Wait";
  delay?: Units.Time;
	constructor({delay = undefined}: Partial<{delay: Units.Time}>) {
    this.delay = delay;
  }
  /** Adds this command to the current auto and returns itself for chaining. */
  add(): this {
    _addCommandHook?.(this);
    return this;
  }
}

export class Print {
  type: "Print" = "Print";
  message?: string;
	constructor({message = ""}: Partial<{message: string}>) {
    this.message = message;
  }
  /** Adds this command to the current auto and returns itself for chaining. */
  add(): this {
    _addCommandHook?.(this);
    return this;
  }
}

export class Rotation2d {
  degrees?: number;
	constructor({degrees = 0}: Partial<{degrees: number}>) {
    this.degrees = degrees;
  }
}

export class Translation2d {
  x?: number;
  y?: number;
	constructor({x = 0, y = 0}: Partial<{x: number; y: number}>) {
    this.x = x;
    this.y = y;
  }
}

export class Pose2d {
  rotation?: Rotation2d;
  translation?: Translation2d;
	constructor({rotation = new Rotation2d({}), translation = new Translation2d({})}: Partial<{rotation: Rotation2d; translation: Translation2d}>) {
    this.rotation = rotation;
    this.translation = translation;
  }
}

export class APTarget {
  reference?: Pose2d;
  entryAngle?: Rotation2d | undefined;
  velocity?: number;
  rotationRadius?: Units.Distance | undefined;
	constructor({reference = new Pose2d({}), entryAngle = undefined, velocity = 0, rotationRadius = undefined}: Partial<{reference: Pose2d; entryAngle: Rotation2d; velocity: number; rotationRadius: Units.Distance}>) {
    this.reference = reference;
    this.entryAngle = entryAngle;
    this.velocity = velocity;
    this.rotationRadius = rotationRadius;
  }
}

export class APConstraints {
  velocity?: number;
  acceleration?: number;
  jerk?: number;
	constructor({velocity = 0, acceleration = 0, jerk = 0}: Partial<{velocity: number; acceleration: number; jerk: number}>) {
    this.velocity = velocity;
    this.acceleration = acceleration;
    this.jerk = jerk;
  }
}

export class APProfile {
  constraints?: APConstraints;
  errorXY?: Units.Distance;
  errorTheta?: Units.Angle;
  beelineRadius?: Units.Distance;
	constructor({constraints = new APConstraints({}), errorXY = undefined, errorTheta = undefined, beelineRadius = undefined}: Partial<{constraints: APConstraints; errorXY: Units.Distance; errorTheta: Units.Angle; beelineRadius: Units.Distance}>) {
    this.constraints = constraints;
    this.errorXY = errorXY;
    this.errorTheta = errorTheta;
    this.beelineRadius = beelineRadius;
  }
}

export class PIDGains {
  kP?: number;
  kI?: number;
  kD?: number;
  kS?: number;
  kG?: number;
  kV?: number;
  kA?: number;
	constructor({kP = 0, kI = 0, kD = 0, kS = 0, kG = 0, kV = 0, kA = 0}: Partial<{kP: number; kI: number; kD: number; kS: number; kG: number; kV: number; kA: number}>) {
    this.kP = kP;
    this.kI = kI;
    this.kD = kD;
    this.kS = kS;
    this.kG = kG;
    this.kV = kV;
    this.kA = kA;
  }
}

export class AutoPilotAction {
  type: "AutoPilotAction" = "AutoPilotAction";
  target?: APTarget;
  profile?: APProfile | undefined;
  constraints?: APConstraints | undefined;
  pidGains?: PIDGains | undefined;
  allianceRelative?: boolean | undefined;
	constructor({target = new APTarget({}), profile = undefined, constraints = undefined, pidGains = undefined, allianceRelative = undefined}: Partial<{target: APTarget; profile: APProfile; constraints: APConstraints; pidGains: PIDGains; allianceRelative: boolean}>) {
    this.target = target;
    this.profile = profile;
    this.constraints = constraints;
    this.pidGains = pidGains;
    this.allianceRelative = allianceRelative;
  }
  /** Adds this command to the current auto and returns itself for chaining. */
  add(): this {
    _addCommandHook?.(this);
    return this;
  }
}

export class XBasedAutoPilotAction {
  type: "XBasedAutoPilotAction" = "XBasedAutoPilotAction";
  target?: APTarget;
  profile?: APProfile | undefined;
  constraints?: APConstraints | undefined;
  pidGains?: PIDGains | undefined;
  allianceRelative?: boolean | undefined;
	constructor({target = new APTarget({}), profile = undefined, constraints = undefined, pidGains = undefined, allianceRelative = undefined}: Partial<{target: APTarget; profile: APProfile; constraints: APConstraints; pidGains: PIDGains; allianceRelative: boolean}>) {
    this.target = target;
    this.profile = profile;
    this.constraints = constraints;
    this.pidGains = pidGains;
    this.allianceRelative = allianceRelative;
  }
  /** Adds this command to the current auto and returns itself for chaining. */
  add(): this {
    _addCommandHook?.(this);
    return this;
  }
}

export class StopDriveAction {
  type: "StopDriveAction" = "StopDriveAction";
	constructor({}: Partial<{}>) {
  }
  /** Adds this command to the current auto and returns itself for chaining. */
  add(): this {
    _addCommandHook?.(this);
    return this;
  }
}

export class DeployIntakeAction {
  type: "DeployIntakeAction" = "DeployIntakeAction";
	constructor({}: Partial<{}>) {
  }
  /** Adds this command to the current auto and returns itself for chaining. */
  add(): this {
    _addCommandHook?.(this);
    return this;
  }
}

export class StowIntakeAction {
  type: "StowIntakeAction" = "StowIntakeAction";
	constructor({}: Partial<{}>) {
  }
  /** Adds this command to the current auto and returns itself for chaining. */
  add(): this {
    _addCommandHook?.(this);
    return this;
  }
}

export type AutoAction = Deadline | Sequence | Parallel | Race | Wait | Print | AutoPilotAction | XBasedAutoPilotAction | StopDriveAction | DeployIntakeAction | StowIntakeAction | undefined | null;

let _addCommandHook: ((command: NonNullable<AutoAction>) => void) | null = null;
export function setAddCommandHook(hook: (command: NonNullable<AutoAction>) => void) { _addCommandHook = hook; }
export class Transform2d {
  rotation?: Rotation2d;
  translation?: Translation2d;
	constructor({rotation = new Rotation2d({}), translation = new Translation2d({})}: Partial<{rotation: Rotation2d; translation: Translation2d}>) {
    this.rotation = rotation;
    this.translation = translation;
  }
}

export class Rotation3d {
  roll?: number;
  pitch?: number;
  yaw?: number;
	constructor({roll = 0, pitch = 0, yaw = 0}: Partial<{roll: number; pitch: number; yaw: number}>) {
    this.roll = roll;
    this.pitch = pitch;
    this.yaw = yaw;
  }
}

export class Translation3d {
  x?: number;
  y?: number;
  z?: number;
	constructor({x = 0, y = 0, z = 0}: Partial<{x: number; y: number; z: number}>) {
    this.x = x;
    this.y = y;
    this.z = z;
  }
}

export class Transform3d {
  rotation?: Rotation3d;
  translation?: Translation3d;
	constructor({rotation = new Rotation3d({}), translation = new Translation3d({})}: Partial<{rotation: Rotation3d; translation: Translation3d}>) {
    this.rotation = rotation;
    this.translation = translation;
  }
}

export class Pose3d {
  rotation?: Rotation3d;
  translation?: Translation3d;
	constructor({rotation = new Rotation3d({}), translation = new Translation3d({})}: Partial<{rotation: Rotation3d; translation: Translation3d}>) {
    this.rotation = rotation;
    this.translation = translation;
  }
}

