// This file is auto-generated by TypeScriptGenerator. Do not edit manually.

class UnitType<UnitTypeName extends string> {
	constructor(public name: UnitTypeName) {}
}

export type Measure<MUnitType extends UnitType<any>> = {
	value: number;
	unit: string;
	_unitType?: MUnitType;
} | null | undefined;

export class Unit<UUnitType extends UnitType<any>>{
	constructor(public name: string, public unitType: UUnitType) {}
	of(value: number): Measure<UUnitType> {
		return { value, unit: this.name, _unitType: this.unitType } as Measure<UUnitType>;
	}
}

export class AngularAcceleration_UnitType extends UnitType<"AngularAcceleration"> {}
export type AngularAcceleration =  Measure<AngularAcceleration_UnitType>;
export const Rotation_per_Second_per_Second = new Unit<AngularAcceleration_UnitType>("Rotation per Second per Second", new AngularAcceleration_UnitType("AngularAcceleration"));
export class Voltage_UnitType extends UnitType<"Voltage"> {}
export type Voltage =  Measure<Voltage_UnitType>;
export const Volt = new Unit<Voltage_UnitType>("Volt", new Voltage_UnitType("Voltage"));
export class LinearAcceleration_UnitType extends UnitType<"LinearAcceleration"> {}
export type LinearAcceleration =  Measure<LinearAcceleration_UnitType>;
export const Meter_per_Second_per_Second = new Unit<LinearAcceleration_UnitType>("Meter per Second per Second", new LinearAcceleration_UnitType("LinearAcceleration"));
export class Time_UnitType extends UnitType<"Time"> {}
export type Time =  Measure<Time_UnitType>;
export const Minute = new Unit<Time_UnitType>("Minute", new Time_UnitType("Time"));
export const Foot_per_Second_per_Second = new Unit<LinearAcceleration_UnitType>("Foot per Second per Second", new LinearAcceleration_UnitType("LinearAcceleration"));
export class AngularVelocity_UnitType extends UnitType<"AngularVelocity"> {}
export type AngularVelocity =  Measure<AngularVelocity_UnitType>;
export const Degree_per_Second = new Unit<AngularVelocity_UnitType>("Degree per Second", new AngularVelocity_UnitType("AngularVelocity"));
export class Torque_UnitType extends UnitType<"Torque"> {}
export type Torque =  Measure<Torque_UnitType>;
export const Inch_Pound_force = new Unit<Torque_UnitType>("Inch-Pound-force", new Torque_UnitType("Torque"));
export const Radian_per_Second = new Unit<AngularVelocity_UnitType>("Radian per Second", new AngularVelocity_UnitType("AngularVelocity"));
export class Frequency_UnitType extends UnitType<"Frequency"> {}
export type Frequency =  Measure<Frequency_UnitType>;
export const Hertz = new Unit<Frequency_UnitType>("Hertz", new Frequency_UnitType("Frequency"));
export class Distance_UnitType extends UnitType<"Distance"> {}
export type Distance =  Measure<Distance_UnitType>;
export const Centimeter = new Unit<Distance_UnitType>("Centimeter", new Distance_UnitType("Distance"));
export const Inch_Ounce_force = new Unit<Torque_UnitType>("Inch-Ounce-force", new Torque_UnitType("Torque"));
export class LinearVelocity_UnitType extends UnitType<"LinearVelocity"> {}
export type LinearVelocity =  Measure<LinearVelocity_UnitType>;
export const Inch_per_Second = new Unit<LinearVelocity_UnitType>("Inch per Second", new LinearVelocity_UnitType("LinearVelocity"));
export const Meter_Newton = new Unit<Torque_UnitType>("Meter-Newton", new Torque_UnitType("Torque"));
export const Degree_per_Second_per_Second = new Unit<AngularAcceleration_UnitType>("Degree per Second per Second", new AngularAcceleration_UnitType("AngularAcceleration"));
export class Power_UnitType extends UnitType<"Power"> {}
export type Power =  Measure<Power_UnitType>;
export const Watt = new Unit<Power_UnitType>("Watt", new Power_UnitType("Power"));
export const Rotation_per_Second = new Unit<AngularVelocity_UnitType>("Rotation per Second", new AngularVelocity_UnitType("AngularVelocity"));
export class Current_UnitType extends UnitType<"Current"> {}
export type Current =  Measure<Current_UnitType>;
export const Amp = new Unit<Current_UnitType>("Amp", new Current_UnitType("Current"));
export class Force_UnitType extends UnitType<"Force"> {}
export type Force =  Measure<Force_UnitType>;
export const Newton = new Unit<Force_UnitType>("Newton", new Force_UnitType("Force"));
export class Temperature_UnitType extends UnitType<"Temperature"> {}
export type Temperature =  Measure<Temperature_UnitType>;
export const Celsius = new Unit<Temperature_UnitType>("Celsius", new Temperature_UnitType("Temperature"));
export const Fahrenheit = new Unit<Temperature_UnitType>("Fahrenheit", new Temperature_UnitType("Temperature"));
export const G = new Unit<LinearAcceleration_UnitType>("G", new LinearAcceleration_UnitType("LinearAcceleration"));
export const Inch = new Unit<Distance_UnitType>("Inch", new Distance_UnitType("Distance"));
export const Foot_per_Second = new Unit<LinearVelocity_UnitType>("Foot per Second", new LinearVelocity_UnitType("LinearVelocity"));
export class Energy_UnitType extends UnitType<"Energy"> {}
export type Energy =  Measure<Energy_UnitType>;
export const Joule = new Unit<Energy_UnitType>("Joule", new Energy_UnitType("Energy"));
export const Kelvin = new Unit<Temperature_UnitType>("Kelvin", new Temperature_UnitType("Temperature"));
export const Rotation_per_Minute = new Unit<AngularVelocity_UnitType>("Rotation per Minute", new AngularVelocity_UnitType("AngularVelocity"));
export class LinearMomentum_UnitType extends UnitType<"LinearMomentum"> {}
export type LinearMomentum =  Measure<LinearMomentum_UnitType>;
export const Kilogram_Meter_per_Second = new Unit<LinearMomentum_UnitType>("Kilogram-Meter per Second", new LinearMomentum_UnitType("LinearMomentum"));
export class Resistance_UnitType extends UnitType<"Resistance"> {}
export type Resistance =  Measure<Resistance_UnitType>;
export const Kiloohm = new Unit<Resistance_UnitType>("Kiloohm", new Resistance_UnitType("Resistance"));
export class Mass_UnitType extends UnitType<"Mass"> {}
export type Mass =  Measure<Mass_UnitType>;
export const Gram = new Unit<Mass_UnitType>("Gram", new Mass_UnitType("Mass"));
export const Millimeter = new Unit<Distance_UnitType>("Millimeter", new Distance_UnitType("Distance"));
export const Millihertz = new Unit<Frequency_UnitType>("Millihertz", new Frequency_UnitType("Frequency"));
export const Millijoule = new Unit<Energy_UnitType>("Millijoule", new Energy_UnitType("Energy"));
export class Angle_UnitType extends UnitType<"Angle"> {}
export type Angle =  Measure<Angle_UnitType>;
export const Degree = new Unit<Angle_UnitType>("Degree", new Angle_UnitType("Angle"));
export const Rotation = new Unit<Angle_UnitType>("Rotation", new Angle_UnitType("Angle"));
export const Foot_Pound_force = new Unit<Torque_UnitType>("Foot-Pound-force", new Torque_UnitType("Torque"));
export const Microsecond = new Unit<Time_UnitType>("Microsecond", new Time_UnitType("Time"));
export const Radian_per_Second_per_Second = new Unit<AngularAcceleration_UnitType>("Radian per Second per Second", new AngularAcceleration_UnitType("AngularAcceleration"));
export const Revolution_per_Second = new Unit<AngularVelocity_UnitType>("Revolution per Second", new AngularVelocity_UnitType("AngularVelocity"));
export const Millivolt = new Unit<Voltage_UnitType>("Millivolt", new Voltage_UnitType("Voltage"));
export const Revolution = new Unit<Angle_UnitType>("Revolution", new Angle_UnitType("Angle"));
export const Kilogram = new Unit<Mass_UnitType>("Kilogram", new Mass_UnitType("Mass"));
export const Kilojoule = new Unit<Energy_UnitType>("Kilojoule", new Energy_UnitType("Energy"));
export const Radian = new Unit<Angle_UnitType>("Radian", new Angle_UnitType("Angle"));
export const Milliwatt = new Unit<Power_UnitType>("Milliwatt", new Power_UnitType("Power"));
export const Foot = new Unit<Distance_UnitType>("Foot", new Distance_UnitType("Distance"));
export class AngularMomentum_UnitType extends UnitType<"AngularMomentum"> {}
export type AngularMomentum =  Measure<AngularMomentum_UnitType>;
export const Kilogram_Meter_per_Second_Meter = new Unit<AngularMomentum_UnitType>("Kilogram-Meter per Second-Meter", new AngularMomentum_UnitType("AngularMomentum"));
export class MomentOfInertia_UnitType extends UnitType<"MomentOfInertia"> {}
export type MomentOfInertia =  Measure<MomentOfInertia_UnitType>;
export const Kilogram_Meter_per_Second_Meter_per_Radian_per_Second = new Unit<MomentOfInertia_UnitType>("Kilogram-Meter per Second-Meter per Radian per Second", new MomentOfInertia_UnitType("MomentOfInertia"));
export const Milliohm = new Unit<Resistance_UnitType>("Milliohm", new Resistance_UnitType("Resistance"));
export class Dimensionless_UnitType extends UnitType<"Dimensionless"> {}
export type Dimensionless =  Measure<Dimensionless_UnitType>;
export const Percent = new Unit<Dimensionless_UnitType>("Percent", new Dimensionless_UnitType("Dimensionless"));
export const Millisecond = new Unit<Time_UnitType>("Millisecond", new Time_UnitType("Time"));
export const Pound = new Unit<Mass_UnitType>("Pound", new Mass_UnitType("Mass"));
export const Second = new Unit<Time_UnitType>("Second", new Time_UnitType("Time"));
export const Meter = new Unit<Distance_UnitType>("Meter", new Distance_UnitType("Distance"));
export const Horsepower = new Unit<Power_UnitType>("Horsepower", new Power_UnitType("Power"));
export const Meter_per_Second = new Unit<LinearVelocity_UnitType>("Meter per Second", new LinearVelocity_UnitType("LinearVelocity"));
export const Milliamp = new Unit<Current_UnitType>("Milliamp", new Current_UnitType("Current"));
export const Ounce = new Unit<Mass_UnitType>("Ounce", new Mass_UnitType("Mass"));
export const Unitless = new Unit<Dimensionless_UnitType>("<?>", new Dimensionless_UnitType("Dimensionless"));
export const Ohm = new Unit<Resistance_UnitType>("Ohm", new Resistance_UnitType("Resistance"));
export const Ounce_force = new Unit<Force_UnitType>("Ounce-force", new Force_UnitType("Force"));
export const Pound_force = new Unit<Force_UnitType>("Pound-force", new Force_UnitType("Force"));
export class Velocity_UnitType extends UnitType<"Velocity"> {}
export type Velocity =  Measure<Velocity_UnitType>;
export const Rotation_per_Second_per_Second_per_Second = new Unit<Velocity_UnitType>("Rotation per Second per Second per Second", new Velocity_UnitType("Velocity"));
