// This file is auto-generated by TypeScriptGenerator. Do not edit manually.

class UnitType<UnitTypeName extends string> {
	constructor(public name: UnitTypeName) {}
}

export type Measure<MUnitType extends UnitType<any>> = {
	value: number;
	unit: string;
	_unitType?: MUnitType;
} | null | undefined;

export class Unit<UUnitType extends UnitType<any>>{
	constructor(public name: string, public unitType: UUnitType) {}
	of(value: number): Measure<UUnitType> {
		return { value, unit: this.name, _unitType: this.unitType } as Measure<UUnitType>;
	}
}

export class AngularVelocityPerTime_UnitType extends UnitType<"AngularVelocityPerTime"> {}
export type AngularVelocityPerTime =  Measure<AngularVelocityPerTime_UnitType>;
export const Rotation_per_Second_per_Second = new Unit<AngularVelocityPerTime_UnitType>("Rotation per Second per Second", new AngularVelocityPerTime_UnitType("AngularVelocityPerTime"));
export class CurrentPerTime_UnitType extends UnitType<"CurrentPerTime"> {}
export type CurrentPerTime =  Measure<CurrentPerTime_UnitType>;
export const Amp_per_Second = new Unit<CurrentPerTime_UnitType>("Amp per Second", new CurrentPerTime_UnitType("CurrentPerTime"));
export class Voltage_UnitType extends UnitType<"Voltage"> {}
export type Voltage =  Measure<Voltage_UnitType>;
export const Volt = new Unit<Voltage_UnitType>("Volt", new Voltage_UnitType("Voltage"));
export class LinearVelocityPerTime_UnitType extends UnitType<"LinearVelocityPerTime"> {}
export type LinearVelocityPerTime =  Measure<LinearVelocityPerTime_UnitType>;
export const Meter_per_Second_per_Second = new Unit<LinearVelocityPerTime_UnitType>("Meter per Second per Second", new LinearVelocityPerTime_UnitType("LinearVelocityPerTime"));
export class Time_UnitType extends UnitType<"Time"> {}
export type Time =  Measure<Time_UnitType>;
export const Minute = new Unit<Time_UnitType>("Minute", new Time_UnitType("Time"));
export const Foot_per_Second_per_Second = new Unit<LinearVelocityPerTime_UnitType>("Foot per Second per Second", new LinearVelocityPerTime_UnitType("LinearVelocityPerTime"));
export class AnglePerTime_UnitType extends UnitType<"AnglePerTime"> {}
export type AnglePerTime =  Measure<AnglePerTime_UnitType>;
export const Degree_per_Second = new Unit<AnglePerTime_UnitType>("Degree per Second", new AnglePerTime_UnitType("AnglePerTime"));
export class Torque_UnitType extends UnitType<"Torque"> {}
export type Torque =  Measure<Torque_UnitType>;
export const Inch_Pound_force = new Unit<Torque_UnitType>("Inch-Pound-force", new Torque_UnitType("Torque"));
export const Radian_per_Second = new Unit<AnglePerTime_UnitType>("Radian per Second", new AnglePerTime_UnitType("AnglePerTime"));
export class VoltagePerLinearAcceleration_UnitType extends UnitType<"VoltagePerLinearAcceleration"> {}
export type VoltagePerLinearAcceleration =  Measure<VoltagePerLinearAcceleration_UnitType>;
export const Volt_per_Meter_per_Second_per_Second = new Unit<VoltagePerLinearAcceleration_UnitType>("Volt per Meter per Second per Second", new VoltagePerLinearAcceleration_UnitType("VoltagePerLinearAcceleration"));
export class DimensionlessPerTime_UnitType extends UnitType<"DimensionlessPerTime"> {}
export type DimensionlessPerTime =  Measure<DimensionlessPerTime_UnitType>;
export const Hertz = new Unit<DimensionlessPerTime_UnitType>("Hertz", new DimensionlessPerTime_UnitType("DimensionlessPerTime"));
export class Distance_UnitType extends UnitType<"Distance"> {}
export type Distance =  Measure<Distance_UnitType>;
export const Centimeter = new Unit<Distance_UnitType>("Centimeter", new Distance_UnitType("Distance"));
export const Inch_Ounce_force = new Unit<Torque_UnitType>("Inch-Ounce-force", new Torque_UnitType("Torque"));
export class DistancePerTime_UnitType extends UnitType<"DistancePerTime"> {}
export type DistancePerTime =  Measure<DistancePerTime_UnitType>;
export const Inch_per_Second = new Unit<DistancePerTime_UnitType>("Inch per Second", new DistancePerTime_UnitType("DistancePerTime"));
export const Meter_Newton = new Unit<Torque_UnitType>("Meter-Newton", new Torque_UnitType("Torque"));
export const Degree_per_Second_per_Second = new Unit<AngularVelocityPerTime_UnitType>("Degree per Second per Second", new AngularVelocityPerTime_UnitType("AngularVelocityPerTime"));
export class EnergyPerTime_UnitType extends UnitType<"EnergyPerTime"> {}
export type EnergyPerTime =  Measure<EnergyPerTime_UnitType>;
export const Watt = new Unit<EnergyPerTime_UnitType>("Watt", new EnergyPerTime_UnitType("EnergyPerTime"));
export const Rotation_per_Second = new Unit<AnglePerTime_UnitType>("Rotation per Second", new AnglePerTime_UnitType("AnglePerTime"));
export class Current_UnitType extends UnitType<"Current"> {}
export type Current =  Measure<Current_UnitType>;
export const Amp = new Unit<Current_UnitType>("Amp", new Current_UnitType("Current"));
export class Force_UnitType extends UnitType<"Force"> {}
export type Force =  Measure<Force_UnitType>;
export const Newton = new Unit<Force_UnitType>("Newton", new Force_UnitType("Force"));
export class Temperature_UnitType extends UnitType<"Temperature"> {}
export type Temperature =  Measure<Temperature_UnitType>;
export const Celsius = new Unit<Temperature_UnitType>("Celsius", new Temperature_UnitType("Temperature"));
export const Fahrenheit = new Unit<Temperature_UnitType>("Fahrenheit", new Temperature_UnitType("Temperature"));
export const G = new Unit<LinearVelocityPerTime_UnitType>("G", new LinearVelocityPerTime_UnitType("LinearVelocityPerTime"));
export const Inch = new Unit<Distance_UnitType>("Inch", new Distance_UnitType("Distance"));
export const Foot_per_Second = new Unit<DistancePerTime_UnitType>("Foot per Second", new DistancePerTime_UnitType("DistancePerTime"));
export class Energy_UnitType extends UnitType<"Energy"> {}
export type Energy =  Measure<Energy_UnitType>;
export const Joule = new Unit<Energy_UnitType>("Joule", new Energy_UnitType("Energy"));
export const Kelvin = new Unit<Temperature_UnitType>("Kelvin", new Temperature_UnitType("Temperature"));
export const Rotation_per_Minute = new Unit<AnglePerTime_UnitType>("Rotation per Minute", new AnglePerTime_UnitType("AnglePerTime"));
export class LinearMomentum_UnitType extends UnitType<"LinearMomentum"> {}
export type LinearMomentum =  Measure<LinearMomentum_UnitType>;
export const Kilogram_Meter_per_Second = new Unit<LinearMomentum_UnitType>("Kilogram-Meter per Second", new LinearMomentum_UnitType("LinearMomentum"));
export class VoltagePerCurrent_UnitType extends UnitType<"VoltagePerCurrent"> {}
export type VoltagePerCurrent =  Measure<VoltagePerCurrent_UnitType>;
export const Kiloohm = new Unit<VoltagePerCurrent_UnitType>("Kiloohm", new VoltagePerCurrent_UnitType("VoltagePerCurrent"));
export class Mass_UnitType extends UnitType<"Mass"> {}
export type Mass =  Measure<Mass_UnitType>;
export const Gram = new Unit<Mass_UnitType>("Gram", new Mass_UnitType("Mass"));
export const Millimeter = new Unit<Distance_UnitType>("Millimeter", new Distance_UnitType("Distance"));
export const Millihertz = new Unit<DimensionlessPerTime_UnitType>("Millihertz", new DimensionlessPerTime_UnitType("DimensionlessPerTime"));
export const Millijoule = new Unit<Energy_UnitType>("Millijoule", new Energy_UnitType("Energy"));
export class Angle_UnitType extends UnitType<"Angle"> {}
export type Angle =  Measure<Angle_UnitType>;
export const Degree = new Unit<Angle_UnitType>("Degree", new Angle_UnitType("Angle"));
export const Rotation = new Unit<Angle_UnitType>("Rotation", new Angle_UnitType("Angle"));
export const Foot_Pound_force = new Unit<Torque_UnitType>("Foot-Pound-force", new Torque_UnitType("Torque"));
export const Microsecond = new Unit<Time_UnitType>("Microsecond", new Time_UnitType("Time"));
export const Radian_per_Second_per_Second = new Unit<AngularVelocityPerTime_UnitType>("Radian per Second per Second", new AngularVelocityPerTime_UnitType("AngularVelocityPerTime"));
export const Revolution_per_Second = new Unit<AnglePerTime_UnitType>("Revolution per Second", new AnglePerTime_UnitType("AnglePerTime"));
export const Millivolt = new Unit<Voltage_UnitType>("Millivolt", new Voltage_UnitType("Voltage"));
export const Rotation_per_Minute_per_Second = new Unit<AngularVelocityPerTime_UnitType>("Rotation per Minute per Second", new AngularVelocityPerTime_UnitType("AngularVelocityPerTime"));
export const Revolution = new Unit<Angle_UnitType>("Revolution", new Angle_UnitType("Angle"));
export const Kilogram = new Unit<Mass_UnitType>("Kilogram", new Mass_UnitType("Mass"));
export const Kilojoule = new Unit<Energy_UnitType>("Kilojoule", new Energy_UnitType("Energy"));
export const Radian = new Unit<Angle_UnitType>("Radian", new Angle_UnitType("Angle"));
export const Milliwatt = new Unit<EnergyPerTime_UnitType>("Milliwatt", new EnergyPerTime_UnitType("EnergyPerTime"));
export const Foot = new Unit<Distance_UnitType>("Foot", new Distance_UnitType("Distance"));
export class AngularMomentum_UnitType extends UnitType<"AngularMomentum"> {}
export type AngularMomentum =  Measure<AngularMomentum_UnitType>;
export const Kilogram_Meter_per_Second_Meter = new Unit<AngularMomentum_UnitType>("Kilogram-Meter per Second-Meter", new AngularMomentum_UnitType("AngularMomentum"));
export class AngularMomentumPerAngularVelocity_UnitType extends UnitType<"AngularMomentumPerAngularVelocity"> {}
export type AngularMomentumPerAngularVelocity =  Measure<AngularMomentumPerAngularVelocity_UnitType>;
export const Kilogram_Meter_per_Second_Meter_per_Radian_per_Second = new Unit<AngularMomentumPerAngularVelocity_UnitType>("Kilogram-Meter per Second-Meter per Radian per Second", new AngularMomentumPerAngularVelocity_UnitType("AngularMomentumPerAngularVelocity"));
export const Milliohm = new Unit<VoltagePerCurrent_UnitType>("Milliohm", new VoltagePerCurrent_UnitType("VoltagePerCurrent"));
export const Volt_per_Radian_per_Second_per_Second = new Unit<VoltagePerLinearAcceleration_UnitType>("Volt per Radian per Second per Second", new VoltagePerLinearAcceleration_UnitType("VoltagePerLinearAcceleration"));
export const Volt_per_Radian_per_Second = new Unit<VoltagePerLinearAcceleration_UnitType>("Volt per Radian per Second", new VoltagePerLinearAcceleration_UnitType("VoltagePerLinearAcceleration"));
export class Dimensionless_UnitType extends UnitType<"Dimensionless"> {}
export type Dimensionless =  Measure<Dimensionless_UnitType>;
export const Percent = new Unit<Dimensionless_UnitType>("Percent", new Dimensionless_UnitType("Dimensionless"));
export const Millisecond = new Unit<Time_UnitType>("Millisecond", new Time_UnitType("Time"));
export const Pound = new Unit<Mass_UnitType>("Pound", new Mass_UnitType("Mass"));
export const Second = new Unit<Time_UnitType>("Second", new Time_UnitType("Time"));
export const Meter = new Unit<Distance_UnitType>("Meter", new Distance_UnitType("Distance"));
export const Horsepower = new Unit<EnergyPerTime_UnitType>("Horsepower", new EnergyPerTime_UnitType("EnergyPerTime"));
export const Meter_per_Second = new Unit<DistancePerTime_UnitType>("Meter per Second", new DistancePerTime_UnitType("DistancePerTime"));
export const Milliamp = new Unit<Current_UnitType>("Milliamp", new Current_UnitType("Current"));
export const Ounce = new Unit<Mass_UnitType>("Ounce", new Mass_UnitType("Mass"));
export const Unitless = new Unit<Dimensionless_UnitType>("<?>", new Dimensionless_UnitType("Dimensionless"));
export const Ohm = new Unit<VoltagePerCurrent_UnitType>("Ohm", new VoltagePerCurrent_UnitType("VoltagePerCurrent"));
export const Ounce_force = new Unit<Force_UnitType>("Ounce-force", new Force_UnitType("Force"));
export const Pound_force = new Unit<Force_UnitType>("Pound-force", new Force_UnitType("Force"));
export const Rotation_per_Second_per_Second_per_Second = new Unit<CurrentPerTime_UnitType>("Rotation per Second per Second per Second", new CurrentPerTime_UnitType("CurrentPerTime"));
export const Volt_per_Meter_per_Second = new Unit<VoltagePerLinearAcceleration_UnitType>("Volt per Meter per Second", new VoltagePerLinearAcceleration_UnitType("VoltagePerLinearAcceleration"));
