export type Measure = {
  value: number;
  unit: string;
};

export class Unit<M extends Measure>{
	constructor(public name: string) {}
	of(value: number): M {
		return { value, unit: this.name } as M;
	}
}
export type AngularAcceleration = Measure;
export const Rotation_per_Second_per_Second = new Unit<AngularAcceleration>("Rotation per Second per Second");
export type Voltage = Measure;
export const Volt = new Unit<Voltage>("Volt");
export type LinearAcceleration = Measure;
export const Meter_per_Second_per_Second = new Unit<LinearAcceleration>("Meter per Second per Second");
export type Time = Measure;
export const Minute = new Unit<Time>("Minute");
export const Foot_per_Second_per_Second = new Unit<LinearAcceleration>("Foot per Second per Second");
export type AngularVelocity = Measure;
export const Degree_per_Second = new Unit<AngularVelocity>("Degree per Second");
export type Torque = Measure;
export const Inch_Pound_force = new Unit<Torque>("Inch-Pound-force");
export const Radian_per_Second = new Unit<AngularVelocity>("Radian per Second");
export type Frequency = Measure;
export const Hertz = new Unit<Frequency>("Hertz");
export type Distance = Measure;
export const Centimeter = new Unit<Distance>("Centimeter");
export const Inch_Ounce_force = new Unit<Torque>("Inch-Ounce-force");
export type LinearVelocity = Measure;
export const Inch_per_Second = new Unit<LinearVelocity>("Inch per Second");
export const Meter_Newton = new Unit<Torque>("Meter-Newton");
export const Degree_per_Second_per_Second = new Unit<AngularAcceleration>("Degree per Second per Second");
export type Power = Measure;
export const Watt = new Unit<Power>("Watt");
export const Rotation_per_Second = new Unit<AngularVelocity>("Rotation per Second");
export type Current = Measure;
export const Amp = new Unit<Current>("Amp");
export type Force = Measure;
export const Newton = new Unit<Force>("Newton");
export type Temperature = Measure;
export const Celsius = new Unit<Temperature>("Celsius");
export const Fahrenheit = new Unit<Temperature>("Fahrenheit");
export const G = new Unit<LinearAcceleration>("G");
export const Inch = new Unit<Distance>("Inch");
export const Foot_per_Second = new Unit<LinearVelocity>("Foot per Second");
export type Energy = Measure;
export const Joule = new Unit<Energy>("Joule");
export const Kelvin = new Unit<Temperature>("Kelvin");
export const Rotation_per_Minute = new Unit<AngularVelocity>("Rotation per Minute");
export type LinearMomentum = Measure;
export const Kilogram_Meter_per_Second = new Unit<LinearMomentum>("Kilogram-Meter per Second");
export type Resistance = Measure;
export const Kiloohm = new Unit<Resistance>("Kiloohm");
export type Mass = Measure;
export const Gram = new Unit<Mass>("Gram");
export const Millimeter = new Unit<Distance>("Millimeter");
export const Millihertz = new Unit<Frequency>("Millihertz");
export const Millijoule = new Unit<Energy>("Millijoule");
export type Angle = Measure;
export const Degree = new Unit<Angle>("Degree");
export const Rotation = new Unit<Angle>("Rotation");
export const Foot_Pound_force = new Unit<Torque>("Foot-Pound-force");
export const Microsecond = new Unit<Time>("Microsecond");
export const Radian_per_Second_per_Second = new Unit<AngularAcceleration>("Radian per Second per Second");
export const Revolution_per_Second = new Unit<AngularVelocity>("Revolution per Second");
export const Millivolt = new Unit<Voltage>("Millivolt");
export const Revolution = new Unit<Angle>("Revolution");
export const Kilogram = new Unit<Mass>("Kilogram");
export const Kilojoule = new Unit<Energy>("Kilojoule");
export const Radian = new Unit<Angle>("Radian");
export const Milliwatt = new Unit<Power>("Milliwatt");
export const Foot = new Unit<Distance>("Foot");
export type AngularMomentum = Measure;
export const Kilogram_Meter_per_Second_Meter = new Unit<AngularMomentum>("Kilogram-Meter per Second-Meter");
export type MomentOfInertia = Measure;
export const Kilogram_Meter_per_Second_Meter_per_Radian_per_Second = new Unit<MomentOfInertia>("Kilogram-Meter per Second-Meter per Radian per Second");
export const Milliohm = new Unit<Resistance>("Milliohm");
export type Dimensionless = Measure;
export const Percent = new Unit<Dimensionless>("Percent");
export const Millisecond = new Unit<Time>("Millisecond");
export const Pound = new Unit<Mass>("Pound");
export const Second = new Unit<Time>("Second");
export const Meter = new Unit<Distance>("Meter");
export const Horsepower = new Unit<Power>("Horsepower");
export const Meter_per_Second = new Unit<LinearVelocity>("Meter per Second");
export const Milliamp = new Unit<Current>("Milliamp");
export const Ounce = new Unit<Mass>("Ounce");
export const Unitless = new Unit<Dimensionless>("<?>");
export const Ohm = new Unit<Resistance>("Ohm");
export const Ounce_force = new Unit<Force>("Ounce-force");
export const Pound_force = new Unit<Force>("Pound-force");
export type Velocity = Measure;
export const Rotation_per_Second_per_Second_per_Second = new Unit<Velocity>("Rotation per Second per Second per Second");
